import type { AdWhitelistStatus, CommentMediaType, SubredditNotificationLevel, SubredditType } from "../../../api/types/gql"

export interface Subreddit {
	acceptFollowers: boolean,
	allowChatPostCreation?: boolean,
	allowPredictions?: boolean,
	allowPredictionsTournament?: boolean,
	communityIcon: string,
	displayText: string,
	freeFormReports: boolean,
	icon: { url: string, width: number, height: number },
	id: string,
	isChatPostFeatureEnabled?: boolean,
	isNSFW: boolean,
	isQuarantined: boolean,
	name: string,
	primaryColor: string,
	subscribers: number,
	title: string,
	type: Lowercase<SubredditType>,
	/** don't forget trailing slash */
	url: string,
	whitelistStatus: Lowercase<AdWhitelistStatus>,
	wls: 6,
}

export interface SubredditAboutInfo {
	acceptFollowers: boolean,
	accountsActive: number,
	advertiserCategory?: string,
	allOriginalContent?: boolean,
	allowedPostTypes: {
		links: boolean,
		images: boolean,
		videos: boolean,
		text: boolean,
		spoilers: boolean,
		polls: boolean,
		galleries: boolean,
		talks: false
	},
	allowedMediaInComments: CommentMediaType[],
	contentCategory: string,
	/** in seconds */
	created: number,
	detectedLanguage: string | null,
	disableContributorRequests: boolean,
	emojisEnabled: boolean,
	hasExternalAccount: boolean,
	isCrosspostableSubreddit: boolean,
	isMediaInCommentsSettingShown: boolean,
	isMuted: boolean,
	notificationLevel: SubredditNotificationLevel,
	originalContentTagEnabled: boolean,
	publicDescription: string,
	restrictCommenting: boolean,
	restrictPosting: boolean,
	shouldArchivePosts: boolean,
	showMedia: boolean,
	submitLinkLabel: string,
	submitTextLabel: string,
	subscribers: number,
	userIsBanned: boolean,
	userIsContributor: boolean,
	userIsSubscriber: boolean,
	usingNewModmail?: true,
}