import { getVoteStateNum } from "./common";

export const processPost = (data: any) => ({
	adPromotedUserPostIds: [],
	adSupplementaryText: null,
	author: data.author,
	authorId: data.author_fullname,
	authorIsBlocked: data.author,
	belongsTo: {
		id: data.subreddit_id,
		type: "subreddit",
	},
	callToAction: null,
	contentCategories: null,
	contestMode: data.contest_mode,
	created: data.created_utc,
	crosspostParentId: null,
	crosspostRootId: null,
	discussionType: data.discussion_type,
	distinguishType: data.distinguish_type,
	domain: data.domain,
	domainOverride: null,
	events: [],
	eventsOnRender: [],
	flair: data.link_flair_richtext,
	gildings: null,
	goldCount: 0,
	hidden: data.hidden,
	id: data.name,
	impressionId: null,
	impressionIdStr: null,
	isArchived: data.archived,
	isBlank: false,
	isCreatedFromAdsUi: data.is_created_from_ads_ui,
	isCrosspostable: data.is_crosspostable,
	isGildable: false,
	isLocked: data.locked,
	isMediaOnly: data.media_only,
	isMeta: data.is_meta,
	isNSFW: data.over_18,
	isOriginalContent: data.is_original_content,
	isScoreHidden: data.hide_score,
	isSpoiler: data.spoiler,
	isSponsored: false,
	isStickied: data.stickied,
	isSurveyAd: null,
	liveCommentsWebsocket: data.websocket_url,
	media: {
		mediaMetadata: data.media_metadata,
		obfuscated: null,
		richtextContent: data.rtjson,
		rteMode: data.rte_mode ?? "richtext",
		...(data?.preview?.images?.[0]
			? {
				resolutions: data.preview.images[0].resolutions,
				width: data.preview.images[0].source.width,
				height: data.preview.images[0].source.height,
				content: data.preview.images[0].source.url,
				type: "image"
			} : { type: "rtjson" }
		),
	},
	numComments: data.num_comments,
	numCrossposts: data.num_crossposts,
	numDuplicates: data.num_duplicates,
	permalink: data.permalink,
	postCategories: null,
	postId: data.name,
	saved: data.saved,
	score: data.score,
	sendReplies: data.send_replies,
	source: !data.is_reddit_media_domain && data.url.startsWith('http')
		? {
			url: data.url,
			outboundUrl: data.url,
			outboundUrlCreated: 0,
			displayText: data.domain,
			outboundUrlExpiration: Number.MAX_SAFE_INTEGER,
		} : null,
	subcaption: null,
	suggestedSort: data.suggested_sort,
	thumbnail: {
		height: data.thumbnail_height,
		url: data.thumbnail,
		width: data.thumbnail_width,
	},
	title: data.title,
	upvoteRatio: data.upvote_ratio,
	viewCount: 0,
	voteState: getVoteStateNum(data.likes),
});