export const processUserAbout = (data: any) => ({
	[data.name]: {
		accountIcon: data.icon_img,
		awardedLastMonth: null,
		awardeeKarma: 0,
		awarderKarma: 0,
		bannerImage: data.subreddit.banner_img,
		commentKarma: data.comment_karma,
		created: data.created_utc,
		displayName: data.subreddit.display_name,
		displayNamePrefixed: data.subreddit.display_name_prefixed,
		gildedLastMonth: null,
		hasUserProfile: true,
		hasVerifiedEmail: data.has_verified_email,
		iconSize: data.subreddit.icon_size,
		id: `t2_${data.id}`,
		isEmployee: data.is_employee,
		isFollowing: data.subreddit.user_is_subscriber,
		isGold: data.is_gold,
		isMod: data.is_mod,
		isNSFW: data.over_18,
		postKarma: data.link_karma,
		prefShowSnoovatar: data.pref_show_snoovatar,
		profileId: data.subreddit.name,
		totalKarma: data.total_karma,
		url: data.subreddit.url,
		username: data.name,
	}
})