import { addIdentityToState, addPrefsV1ToState } from './addIdentity';
import addUserRels from './addUserRels';
import experiments from './experiments.json';

export const state = {
	pages: {
		profileOverview: {
			chrono: { api: { error: {}, pending: {} }, fetchedTokens: {}, ids: {}, loadMore: {} },
			conversations: {
				api: { error: {}, pending: {} },
				extraComments: { api: { error: {}, pending: {} }, models: {} },
				keyToCommentThreadLinkSets: {},
				keyToHeadCommentId: {},
				keyToPostId: {},
			},
		},
		modHub: {
			approvedSubmitters: {
				api: { error: null, pending: {} },
				fetchedTokens: {},
				loadMore: {},
				models: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: {},
			},
			approvedTalkHosts: { api: { error: null, pending: {} }, fetchedTokens: {}, loadMore: {}, models: {} },
			flairedUsers: {
				api: { error: null, pending: false },
				models: {},
				pageInfo: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: {},
			},
			moderationLog: {
				actionCategories: {},
				actions: { itemOrder: {}, models: {} },
				approximateCount: null,
				endCursor: null,
				hasNextPage: {},
				hasPreviousPage: {},
				moderators: [],
				startCursor: null,
				insightsEntrypoint: null,
			},
			moderators: {
				editableModerators: {},
				editableUserOrder: { data: {}, api: { error: {}, pending: {} } },
				invitedModerators: { api: { error: null, pending: false }, models: {}, userOrder: {} },
				invitePending: {},
				loadMoreModerators: {},
				loadMoreEditableModerators: {},
				models: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: { data: {}, api: { error: {}, pending: {} } },
			},
			modQueue: {
				bulkAction: { api: { error: null, pending: false }, selectedItems: {}, undoLastAction: {} },
				edited: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				moderatedCommunitiesOrder: { after: null, data: [], loaded: false, pending: false },
				modqueue: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				reports: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				spam: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				unmoderated: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
			},
			muted: {
				api: { error: null, pending: {} },
				fetchedTokens: {},
				inContext: null,
				loadMore: {},
				models: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: {},
			},
		},
		comments: {
			api: { error: {}, fullyLoaded: {}, pending: {} },
			followed: [],
			keyToChatCommentLinks: {},
			keyToCommentThreadLinkSets: {},
			keyToHeadCommentId: {},
			keyToPostId: {},
			ads: [],
		},
		topics: { models: {} },
		econManagement: { displayState: "default", currentEntity: null, relatedData: {}, entityTypes: {} },
		followers: { api: { pending: false }, models: {}, pageInfo: null, search: {}, userIds: [] },
		subredditWiki: {
			diff: {},
			directory: {},
			pages: {},
			pageSettings: {},
			revisions: { api: { error: {}, pending: {} }, listings: {}, models: {} },
			wikiBannedContributors: { listing: { afterToken: {}, api: { error: {}, pending: {} }, models: {}, userOrder: {} }, search: {} },
			wikiContributors: { listing: { afterToken: {}, api: { error: {}, pending: {} }, models: {}, userOrder: {} }, search: {} },
		},
	},
	accountManagerModalData: {},
	activeModal: null,
	ads: {},
	adsSignals: { adsSeenCount: 0, totalPostsSeenCount: 0, sessionStartTime: new Date().toISOString() },
	apiRequestState: {},
	appBadges: { api: { error: null, pending: false }, badges: {} },
	authorFlair: { inContext: null, models: {} },
	awards: {
		blacklist: {},
		create: { api: { error: null, pending: false } },
		manageable: { api: { error: null, pending: {} }, availability: {}, order: {} },
		models: {
			gid_1: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 100,
				coinReward: 0,
				description: "Shows the Silver Award... and that's it.",
				daysOfDripExtension: 0,
				icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-silver-medium.png?v=2" },
				staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-silver-medium.png?v=2" },
				id: "gid_1",
				isEnabled: true,
				isNew: false,
				name: "Silver",
				daysOfPremium: 0,
				tiers: null,
			},
			gid_2: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 500,
				coinReward: 100,
				description: "Gives 100 Reddit Coins and a week of r/lounge access and ad-free browsing.",
				daysOfDripExtension: 0,
				icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
				staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
				id: "gid_2",
				isEnabled: true,
				isNew: false,
				name: "Gold",
				daysOfPremium: 7,
				tiers: null,
			},
			gid_3: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 1800,
				coinReward: 0,
				description:
					"Gives a month of free Premium, which includes ad-free browsing, r/lounge access, and 700 Reddit Coins per month, until Coins are sunset on September 12, 2023.",
				daysOfDripExtension: 31,
				icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-platinum-medium.png?v=2" },
				staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-platinum-medium.png?v=2" },
				id: "gid_3",
				isEnabled: true,
				isNew: false,
				name: "Platinum",
				daysOfPremium: 31,
				tiers: null,
			},
			/*
			award_free_bravo: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 0,
				coinReward: 0,
				description: "Bravo",
				daysOfDripExtension: 0,
				icon: { url: "https://i.redd.it/snoovatar/snoo_assets/marketing/IHibp9kp7Rc_bravo_128.png" },
				staticIcon: { url: "https://i.redd.it/snoovatar/snoo_assets/marketing/IHibp9kp7Rc_bravo_128.png" },
				id: "award_free_bravo",
				isEnabled: true,
				isNew: false,
				name: "Bravo",
				daysOfPremium: 0,
				tiers: null,
			},
			award_free_heartwarming: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 0,
				coinReward: 0,
				description: "Heartwarming",
				daysOfDripExtension: 0,
				icon: { url: "https://i.redd.it/snoovatar/snoo_assets/marketing/-IloaLvY3IU_Heartwarming_128.png" },
				staticIcon: { url: "https://i.redd.it/snoovatar/snoo_assets/marketing/-IloaLvY3IU_Heartwarming_128.png" },
				id: "award_free_heartwarming",
				isEnabled: true,
				isNew: false,
				name: "Gold",
				daysOfPremium: 0,
				tiers: null,
			},
			award_free_regret_2: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 0,
				coinReward: 0,
				description: "Regret",
				daysOfDripExtension: 0,
				icon: { url: "https://i.redd.it/snoovatar/snoo_assets/marketing/s-JbdaIL0KU_regret_128.png" },
				staticIcon: { url: "https://i.redd.it/snoovatar/snoo_assets/marketing/s-JbdaIL0KU_regret_128.png" },
				id: "award_free_regret_2",
				isEnabled: true,
				isNew: false,
				name: "Regret",
				daysOfPremium: 0,
				tiers: null,
			},
			*/
		},
		sortedUsable: {
			api: { pending: {} },
			order: {
				t5_c6q4xs: {
					t3_1uouzzo: [
						{ award: { id: "award_free_bravo" }, total: 0 },
						{ award: { id: "award_free_heartwarming" }, total: 0 },
						{ award: { id: "award_free_regret_2" }, total: 0 }
					]
				}
			}
		},
		tags: { order: {} },
		chatReactions: { availability: {}, pending: {} },
	},
	badges: { api: { subreddit: { error: {}, pending: {} }, user: { error: {}, pending: {} } }, models: {} },
	blockedRedditors: { api: { error: { message: "" }, pending: false }, list: { ids: [] } },
	blockUser: { api: { error: {}, pending: {} } },
	brandSafety: { isViewSafe: true, hasBrandSafetyBeenAssessed: false },
	chat: { liveChatTooltipShowState: "never_shown", showChatChannelDiscoveryTooltip: false, activeUserCountByLiveChatId: {}, hasSendbirdChats: null },
	commentsListTruncated: true,
	communityFlairs: {},
	connection: { showBanner: false, online: true },
	contentControls: { api: { fetch: { error: {}, pending: {} } }, models: {} },
	contentGate: {},
	continueThreads: { models: {} },
	creations: {
		api: {
			collection: { createOrUpdate: { error: null, pending: false } },
			draft: {
				deleteDraft: { error: {}, pending: {} },
				listing: { error: null, pending: false },
				save: { error: { apiError: null, needsCaptcha: false, validationError: null, submitValidationError: null }, pending: false },
			},
			editor: { converting: { pending: {} }, mediaUpload: { error: null, pending: false } },
			page: { error: {}, fetched: {}, pending: {} },
			post: {
				submit: { error: { apiError: null, needsCaptcha: false, validationError: null, submitValidationError: null }, pending: false },
				update: { error: null, pending: false },
			},
			subreddit: { change: { error: null, pending: false } },
		},
		drafts: {},
		formData: {
			body: {
				link: "",
				markdown: "",
				media: { items: [], selectedKey: null },
				rte: { isBound: false, editorKey: "7b044e", initialRTJSON: { document: [] } },
			},
			eventSchedule: null,
			flair: null,
			govType: null,
			isChatPost: false,
			isContestMode: false,
			isNSFW: false,
			isOC: false,
			isPostAsMetaMod: false,
			isPoll: false,
			isPublicLink: false,
			isSpoiler: false,
			newSubreddit: "",
			newTopMod: "",
			nextSubreddit: null,
			polls: null,
			postSchedule: null,
			postToTwitter: false,
			recaptcha: "",
			scheduledPostId: null,
			sendReplies: true,
			stickyPosition: null,
			submissionType: "post",
			suggestedSort: null,
			title: "",
			tournament: { name: "", theme: "theme_1", token: null },
			talk: { theme: "periwinkle", topics: [], isUpcoming: false },
		},
		formState: {
			editorMode: null,
			fieldValidation: { title: [], body: [], link: [], flair: [] },
			isChanged: false,
			submitMode: 0,
			postGuidance: { uniqueRules: [], titleTriggeredRules: [], bodyTriggeredRules: [], isBlockRuleTriggered: false, errors: null },
		},
		postEditing: { draft: { markdown: "", rte: { isBound: false, editorKey: "6b9bed", initialRTJSON: { document: [] } } }, postId: null },
		subredditRec: { api: { error: false, pending: false }, isInputChanged: false, model: {}, order: [] },
	},
	dashboard: { selectedComponent: null, subredditPending: false, subredditLoaded: {} },
	discoveryUnits: { api: { list: { error: null, loaded: false, pending: false } }, models: {}, nameToId: {} },
	dismissedTruncationList: [],
	economics: {
		banners: { dismissedBanners: {} },
		currentBadgeManagementScreen: { badgeType: "cosmetic", view: "gallery" },
		currentModalArgs: null,
		emotes: {},
		gifs: {},
		me: { fetched: false, data: {} },
		paymentSystems: { status: 2 },
		pointsCopy: { fetched: false, data: null },
		subredditPremium: {},
	},
	emailVerificationTooltip: { isShowing: false },
	emojis: { api: { list: { pending: {} } }, models: {} },
	experimentOverrides: {},
	externalAccount: {
		api: {
			connect: { error: {}, pending: {} },
			disconnect: { error: {}, pending: {} },
			user: { error: {}, pending: {} },
			subreddit: { error: {}, fetched: {}, pending: {} },
		},
		user: {},
		subreddit: {},
	},
	featureFlags: {
		overrides: {
			introModal: null,
			markdownMode: null,
			modQueue: null,
			spBadges: null,
			spBurnLinks: null,
			spClaimablePoints: null,
			spCustomBadgesAndEmotes: null,
			spCustomCrypto: null,
			spEmotes: null,
			spGiphy: null,
			spGovPolls: null,
			spHarberger: null,
			spLeaderboard: null,
			spPoints: null,
			spPointsCoinConversion: null,
			spPolls: null,
			spPublicPoints: null,
			spSpecialMemberships: null,
			spSpecialMembershipUpsells: null,
			spSpinoffs: null,
			spTipping: null,
			spWalletRegistrationBanner: null,
			scheduledPosts: null,
			adminCommunityTopics: null,
			rteVideoPoster: null,
			devAndStagingWatermark: true,
			fpsMeter: true,
			rabbitHole: null,
			measureScrollFPS: null,
			showVerboseErrors: true,
			srAdoptionWeek: null,
			uappBanner: null,
			experiments: null,
			enableGraphQl: null,
			importExportThemes: null,
			flairRestrictions: null,
			newPostRequirements: null,
			superbOwl: null,
			enableShadowMode: null,
			pushNotificationsBrowserSupported: null,
			enableToxicityWarning: null,
			snoovatar30: null,
			geoSubredditRecommendationDULoggedIn: null,
			geoSubredditRecommendationDULoggedOut: null,
			subredditInlineEditing: true,
			modToMemberShare: null,
			subredditMentionD2xExperiment: null,
			reCaptchaEnterprise: false,
			hatefulContentFiltersEnabled: null,
			__requiredDoNotRemove: null,
		},
	},
	firstPost: {
		currentPromptIndex: 0,
		firstFormEditEvent: false,
		postBody: "",
		postSubmitted: false,
		postTitle: "",
		selectedPredicatesInt: [],
		subreddit: { subredditId: "", subredditName: "" },
	},
	focusedVerticals: {
		api: { error: { focusedVerticalGqlError: null }, pending: { focusedVerticalGqlPending: false } },
		components: { dismissed: true },
		interactedSubredditIds: null,
		recommendedSubredditIds: null,
		category: "",
		lastLoadedEnv: null,
	},
	fontFiles: [],
	frontPageFirstLoaded: true,
	gild: {
		api: { error: null, pending: false, showLoader: false },
		correlationId: null,
		gildModalThingId: null,
		isAnonymous: false,
		isIframed: false,
		message: "",
		gildedThing: null,
		selectedAward: {
			awardType: "GLOBAL",
			awardSubType: "GLOBAL",
			coinPrice: 500,
			coinReward: 100,
			description: "Gives 100 Reddit Coins and a week of r/lounge access and ad-free browsing.",
			daysOfDripExtension: 0,
			icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
			staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
			id: "gid_2",
			isEnabled: true,
			isNew: false,
			name: "Gold",
			daysOfPremium: 7,
			tiers: null,
		},
	},
	header: { isSubscriptionsDropdownOpen: false },
	htmlResponseStreaming: false,
	imageUploads: {},
	impressionMap: {},
	interceptedAction: null,
	isChangeUsernameTooltipShowing: true,
	isModeratorWithPostPerms: false,
	jsApi: [],
	langSite: { bannerClosedTime: 0 },
	leaderboard: { api: { error: {}, pending: {} }, models: {} },
	listings: {
		activeKey: null,
		authorOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		commentOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		communityOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		listingOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		postOrder: {
			api: { error: {}, pending: {} },
			correlationIds: {},
			endMarkers: {},
			fetchedTokens: {},
			ids: {},
			listingSort: {},
			loadMore: {},
			pageInfo: {},
			treatment: {},
		},
	},
	live: { announcements: null, featured: null, isFrontpageLoaded: true, shouldShowAnnouncements: false },
	mediaEmbed: {},
	mediaGalleries: { currentSlideIndex: {}, isGalleryTileLayout: {} },
	mediaPlayback: { isMuted: true, volume: 0.5 },
	merchandisingUnitAnnouncements: [],
	meta: {
		country: "AU",
		region: "NSW",
		city: "Hamilton",
		domain: "www.reddit.com",
		isBot: false,
		isLikelyMod: true,
		isSessionSeo: false,
		method: "GET",
		platform: {
			osName: "windows",
			osVersion: "10",
			browserName: "edge",
			browserVersion: "127-0-0-0",
			primaryLanguage: "en-GB",
			languageList: "en-GB,en;q=0.9,en-US;q=0.8",
		},
		protocol: "https",
		sessionReferrerDomain: "",
		userAgent: navigator.userAgent,
		isOneTapSession: false,
		locale: "en-US",
		pageloadServerTime: 1720786631931,
		samplingBucket: 29.9,
		edgebucket: "yHSvZtREODvfTOTEgn",
	},
	moderatingSubreddits: {},
	modListingPage: { filteredSubreddits: { api: { error: null, pending: false }, names: [] } },
	modModeEnabled: true,
	moreComments: { api: { error: {}, pending: {} }, models: {} },
	multireddits: {
		api: {
			addSubreddit: { error: null, fetched: false, pending: null },
			create: { error: null, fetched: false, pending: false },
			deleteMulti: { error: null, fetched: false, pending: false },
			duplicate: { error: null, fetched: false, pending: false },
			edit: { error: null, fetched: false, pending: false },
			forUser: { fetched: false, pending: false },
			recommendations: { error: null, fetched: false, pending: true },
			removeSubreddit: { error: null, fetched: false, pending: null },
		},
		byUserId: {},
		models: {},
		recommendations: {},
	},
	notificationBannerId: null,
	inactiveModeratorError: false,
	notificationsInbox: {
		api: { error: false, pending: false },
		banner: { banners: [], dismissedBanners: [] },
		earlierDividerIndex: null,
		notifications: [],
		pageInfo: null,
		markAllAsReadTimestamp: null,
	},
	nps: { pending: false, success: false },
	onboarding: { genderUpdateState: { success: false, failure: false }, interestTopicRecommendationsState: null, shouldSkipOnboardingState: false },
	page: {
		experiments: {
			byName: {
				seo_image_descriptive_filenames: { id: 4525, name: "seo_image_descriptive_filenames", variant: "control_1", version: "21" },
				indexing_api_mod_approvals: { id: 5199, name: "indexing_api_mod_approvals", variant: "variant_1", version: "7" },
				seo_indexing_deletes_migration: { id: 7204, name: "seo_indexing_deletes_migration", variant: "enabled", version: "3" },
				seo_indexing_drop_auto_removed: { id: 7912, name: "seo_indexing_drop_auto_removed", variant: "enabled", version: "3" },
				seo_indexing_creates_migration: { id: 8045, name: "seo_indexing_creates_migration", variant: "enabled", version: "3" },
				seo_indexing_updates_migration: { id: 8204, name: "seo_indexing_updates_migration", variant: "enabled", version: "3" },
				shreddit_media_post_link_preview: { id: 8457, name: "shreddit_media_post_link_preview", variant: "enabled", version: "6" },
				shreddit_cdn_media_page_domain_redirect: { id: 8690, name: "shreddit_cdn_media_page_domain_redirect", variant: "enabled", version: "25" },
				seo_mweb3x_bot_footer_inline_styles: { id: 10665, name: "seo_mweb3x_bot_footer_inline_styles", variant: "enabled", version: "4" },
				seo_mt_links: { id: 11267, name: "seo_mt_links", variant: "enabled", version: "8" },
				seo_klp_recommendations: { id: 11330, name: "seo_klp_recommendations", variant: "enabled", version: "7" },
				seo_klp_semantic_recommendations: { id: 11331, name: "seo_klp_semantic_recommendations", variant: "enabled", version: "11" },
				seo_klp_local_klp_store_deprecation: { id: 12925, name: "seo_klp_local_klp_store_deprecation", variant: "enabled", version: "10" },
				i18n_translation_llm_provider: { id: 13258, name: "i18n_translation_llm_provider", variant: "gemini15flash", version: "3" },
				i18n_proactive_translation_indexing: { id: 13638, name: "i18n_proactive_translation_indexing", variant: "control_1", version: "3" },
			},
			canonicalUrl: "https://www.reddit.com/",
		},
	},
	platform: {
		allowNavigationCallback: null,
		currentPage: {
			key: "/",
			locationState: { feedCorrelationId: "b3b8d516-d7d3-47cf-80a2-32908efddf7e" },
			meta: { name: "index", pageType: "home", canonicalPageType: "home" },
			queryParams: {},
			routeMatch: {
				match: { path: "/", url: "/", isExact: true, params: {}, queryParams: {} },
				route: {
					chunk: "Frontpage",
					component: {},
					exact: true,
					prefetches: ["CommentsPage", "Subreddit"],
					path: "/",
					meta: { name: "index", pageType: "home", canonicalPageType: "home" },
				},
			},
			status: 200,
			url: "/",
			urlParams: {},
		},
		lastPage: null,
		referrers: {},
		sessionReferrer: null,
		metas: { "/": { title: "Reddit - Dive into anything" } },
	},
	postCollection: {
		models: {},
		subredditToIds: {},
		api: {
			error: { reorderError: null, updateDescriptionError: null, updateLayoutError: null },
			pending: { reorderPending: false, updateDescriptionPending: false, updateLayoutPending: false },
		},
	},
	polls: { api: { voting: { error: {}, pending: {} } }, models: {}, results: { byVoters: {}, byVotingPower: {} }, rewards: {} },
	postFlair: {} as Record<string, any>,
	posts: {
		embedAndImage: { loadable: {} },
		expanded: {},
		focus: null,
		followed: [],
		instances: {},
		isAnimatingUpvote: null,
		isTrackingCrossposts: {},
		metaMap: {},
		models: {} as Record<string, any>,
		modToMemberShare: null,
		crowdControl: null,
		postLevelCrowdControl: {},
		recent: [],
		scheduledPosts: {
			api: { creationToken: "b5a6b6c2-57fe-402b-bce4-c6099c650459", error: null, pending: true, pendingUpdate: false },
			standalonePosts: { models: {}, pageInfo: {}, postOrder: {} },
			recurringPosts: { models: {}, pageInfo: {}, postOrder: {}, editModal: {} },
		},
		topAwarded: { api: { error: null, pending: false }, list: [] },
		video: {
			autoPlayed: {},
			buffering: {},
			consumed: {},
			continuousViewStartedAt: {},
			feed: { mutedInFeed: true },
			fullscreen: null,
			loadable: {},
			loadTimes: {},
			metadata: {},
			paused: {},
			playing: {},
			started: {},
			time: {},
		},
		carousel: { pending: false, items: {} },
	},
	postGuidance: { api: { fetch: { error: {}, pending: {} } }, models: {}, allowlist: {} },
	postStickiedComments: { data: {} },
	givePremium: { api: { error: null, pending: false }, givePremiumModalAccountName: "" },
	products: { api: { fetch: { error: {}, pending: {} }, purchase: { error: {}, pending: {} } }, currentlyPurchasing: null, models: {} },
	profileCommentsPage: { api: { error: {}, pending: {} }, endMarkers: {}, fetchedTokens: {}, commentIds: {}, loadMore: {} },
	profilePrivatePage: { api: { error: {}, pending: {} }, ids: {}, pageInfo: {} },
	profileModSettingsPage: { api: { pending: true } },
	profilePostsPage: {},
	profiles: {
		about: {},
		models: {},
		moderated: { api: { pending: {} }, models: {}, pageInfo: {} },
		multireddits: { api: { pending: {} }, pageInfo: {} },
		pinnedPosts: { data: {}, initialData: {}, pending: {} },
		trophyCases: {},
	},
	promos: { mobilePromoBanner: false, upsellSignUpBannerLarge: false, upsellSignUpBannerMedium: false, upsellSignUpBannerSmall: null },
	recap: {
		isImageLoading: false,
		isCardsLoading: true,
		cardsLoadingError: null,
		cards: [],
		shareCardWasOpened: false,
		currentCardIndex: 0,
		bannerSeen: true,
		shouldShowShareModal: false,
		shouldHideAbilityCardUsername: false,
		shouldHideAbilityCardAvatar: false,
	},
	recentSubreddits: [],
	recommendations: {},
	reportPage: { reportPageApi: { error: null, pending: false, success: false }, reportPageRules: [], initialReason: null },
	reportRules: { sitewideRules: [] },
	requestHost: "reddit-desktop-external.kubernetes.ue1.snooguts.net",
	runTimeEnvVars: { staging: true, startTimeInMillis: Date.now() },
	search: {
		appliedSort: {},
		isDropdownOpen: false,
		posts: { models: {} },
		searchScope: { enabled: false },
		searchQuery: "",
		typeahead: { idsByQuery: {}, models: {} },
		typeaheadByType: { idsByQuery: {}, models: {} },
		viewTreatment: {},
	},
	searchDiscoveryUnits: { headerContent: {}, models: {}, order: {} },
	searchQueryId: {},
	seo: {
		crawler: null,
		linksModule: JSON.parse('{"frontpage":[{"title":"Popular Communities","links":[{"url":"/r/AskReddit/","visible":true},{"url":"/r/NoStupidQuestions/","visible":true},{"url":"/r/DestinyTheGame/","visible":true},{"url":"/r/explainlikeimfive/","visible":true},{"url":"/r/leagueoflegends/","visible":true},{"url":"/r/Minecraft/","visible":true},{"url":"/r/IAmA/","visible":true},{"url":"/r/OutOfTheLoop/","visible":true},{"url":"/r/discordapp/","visible":true},{"url":"/r/FIFA/","visible":true},{"url":"/r/Instagram/","visible":true},{"url":"/r/Twitch/","visible":true},{"url":"/r/FortNiteBR/","visible":true},{"url":"/r/NintendoSwitch/","visible":true},{"url":"/r/NBA2k/","visible":true},{"url":"/r/gtaonline/","visible":true},{"url":"/r/Tinder/","visible":true},{"url":"/r/xboxone/","visible":true},{"url":"/r/relationship_advice/","visible":true},{"url":"/r/Amd/","visible":true},{"url":"/r/todayilearned/","visible":true},{"url":"/r/sysadmin/","visible":true},{"url":"/r/OnePiece/","visible":true},{"url":"/r/askscience/","visible":true},{"url":"/r/2007scape/","visible":true},{"url":"/r/pics/","visible":true},{"url":"/r/MonsterHunterWorld/","visible":true},{"url":"/r/legaladvice/","visible":true},{"url":"/r/Showerthoughts/","visible":true},{"url":"/r/pcmasterrace/","visible":true},{"url":"/r/LifeProTips/","visible":true},{"url":"/r/breakingbad/","visible":true},{"url":"/r/singapore/","visible":true},{"url":"/r/AskCulinary/","visible":true},{"url":"/r/FORTnITE/","visible":true},{"url":"/r/netflix/","visible":true},{"url":"/r/tipofmytongue/","visible":true},{"url":"/r/DotA2/","visible":true},{"url":"/r/nvidia/","visible":true},{"url":"/r/books/","visible":true},{"url":"/r/DunderMifflin/","visible":true},{"url":"/r/memes/","visible":true},{"url":"/r/baseball/","visible":true},{"url":"/r/learnpython/","visible":true},{"url":"/r/keto/","visible":true},{"url":"/r/Windows10/","visible":true},{"url":"/r/Sneakers/","visible":true},{"url":"/r/Frugal/","visible":true},{"url":"/r/learnprogramming/","visible":true},{"url":"/r/Overwatch/","visible":true},{"url":"/r/southpark/","visible":true},{"url":"/r/piercing/","visible":true},{"url":"/r/canada/","visible":true},{"url":"/r/skyrim/","visible":true},{"url":"/r/worldnews/","visible":true},{"url":"/r/nosleep/","visible":true}]},{"title":"Gaming","links":[{"url":"/r/StardewValley/","visible":true},{"url":"/r/FortniteCompetitive/","visible":true},{"url":"/r/totalwar/","visible":true},{"url":"/r/Fallout/","visible":true},{"url":"/r/RocketLeague/","visible":true},{"url":"/r/fo76/","visible":true},{"url":"/r/yugioh/","visible":true},{"url":"/r/ClashRoyale/","visible":true},{"url":"/r/boardgames/","visible":true},{"url":"/r/thedivision/","visible":true},{"url":"/r/elderscrollsonline/","visible":true},{"url":"/r/runescape/","visible":true},{"url":"/r/Blackops4/","visible":true},{"url":"/r/fireemblem/","visible":true},{"url":"/r/CrusaderKings/","visible":true},{"url":"/r/Breath_of_the_Wild/","visible":true},{"url":"/r/PUBGMobile/","visible":true},{"url":"/r/Warhammer40k/","visible":true},{"url":"/r/Brawlstars/","visible":true},{"url":"/r/summonerswar/","visible":true},{"url":"/r/MLBTheShow/","visible":true},{"url":"/r/SWGalaxyOfHeroes/","visible":true},{"url":"/r/BattlefieldV/","visible":true},{"url":"/r/deadbydaylight/","visible":true},{"url":"/r/MagicArena/","visible":true},{"url":"/r/Smite/","visible":true},{"url":"/r/starcitizen/","visible":true},{"url":"/r/Persona5/","visible":true},{"url":"/r/MortalKombat/","visible":true},{"url":"/r/tf2/","visible":true},{"url":"/r/playrust/","visible":true},{"url":"/r/PSVR/","visible":true},{"url":"/r/RimWorld/","visible":true},{"url":"/r/ClashOfClans/","visible":true},{"url":"/r/FireEmblemHeroes/","visible":true},{"url":"/r/Terraria/","visible":true},{"url":"/r/osugame/","visible":true},{"url":"/r/NoMansSkyTheGame/","visible":true},{"url":"/r/forhonor/","visible":true},{"url":"/r/EliteDangerous/","visible":true},{"url":"/r/Warthunder/","visible":true},{"url":"/r/Seaofthieves/","visible":true},{"url":"/r/Paladins/","visible":true},{"url":"/r/StarWarsBattlefront/","visible":true},{"url":"/r/dauntless/","visible":true},{"url":"/r/FFBraveExvius/","visible":true},{"url":"/r/TwoBestFriendsPlay/","visible":true},{"url":"/r/Competitiveoverwatch/","visible":true},{"url":"/r/DuelLinks/","visible":true},{"url":"/r/Eve/","visible":true},{"url":"/r/danganronpa/","visible":true},{"url":"/r/halo/","visible":true},{"url":"/r/Destiny/","visible":true},{"url":"/r/pesmobile/","visible":true},{"url":"/r/CoDCompetitive/","visible":true},{"url":"/r/future_fight/","visible":true},{"url":"/r/DaysGone/","visible":true},{"url":"/r/ModernMagic/","visible":true},{"url":"/r/girlsfrontline/","visible":true},{"url":"/r/fivenightsatfreddys/","visible":true},{"url":"/r/NHLHUT/","visible":true},{"url":"/r/WorldofTanks/","visible":true},{"url":"/r/Gamingcirclejerk/","visible":true},{"url":"/r/Mordhau/","visible":true},{"url":"/r/battlestations/","visible":true},{"url":"/r/FUTMobile/","visible":true},{"url":"/r/Market76/","visible":true},{"url":"/r/pokemontrades/","visible":true}]},{"title":"Sports","links":[{"url":"/r/soccer/","visible":true},{"url":"/r/hockey/","visible":true},{"url":"/r/CFB/","visible":true},{"url":"/r/barstoolsports/","visible":true},{"url":"/r/airsoft/","visible":true},{"url":"/r/rugbyunion/","visible":true},{"url":"/r/golf/","visible":true},{"url":"/r/MTB/","visible":true},{"url":"/r/cycling/","visible":true},{"url":"/r/Boxing/","visible":true},{"url":"/r/bicycling/","visible":true},{"url":"/r/sportsbook/","visible":true},{"url":"/r/hockeyplayers/","visible":true},{"url":"/r/NewSkaters/","visible":true},{"url":"/r/Astros/","visible":true},{"url":"/r/footballmanagergames/","visible":true},{"url":"/r/WWEGames/","visible":true},{"url":"/r/Nationals/","visible":true},{"url":"/r/GreenBayPackers/","visible":true},{"url":"/r/Patriots/","visible":true},{"url":"/r/sports/","visible":true},{"url":"/r/reddevils/","visible":true},{"url":"/r/LiverpoolFC/","visible":true},{"url":"/r/NYYankees/","visible":true},{"url":"/r/tennis/","visible":true},{"url":"/r/FantasyPL/","visible":true},{"url":"/r/WWE/","visible":true},{"url":"/r/Dodgers/","visible":true},{"url":"/r/NFA/","visible":true},{"url":"/r/eagles/","visible":true},{"url":"/r/sixers/","visible":true},{"url":"/r/Browns/","visible":true},{"url":"/r/detroitlions/","visible":true},{"url":"/r/discgolf/","visible":true},{"url":"/r/Cricket/","visible":true},{"url":"/r/MLS/","visible":true},{"url":"/r/canucks/","visible":true},{"url":"/r/DynastyFF/","visible":true},{"url":"/r/minnesotavikings/","visible":true},{"url":"/r/cowboys/","visible":true},{"url":"/r/snowboarding/","visible":true},{"url":"/r/nrl/","visible":true},{"url":"/r/Braves/","visible":true},{"url":"/r/Cardinals/","visible":true},{"url":"/r/bikecommuting/","visible":true},{"url":"/r/CHIBears/","visible":true},{"url":"/r/ravens/","visible":true},{"url":"/r/coys/","visible":true},{"url":"/r/Mavericks/","visible":true},{"url":"/r/nyjets/","visible":true},{"url":"/r/nbadiscussion/","visible":true},{"url":"/r/chelseafc/","visible":true},{"url":"/r/bostonceltics/","visible":true},{"url":"/r/Fishing/","visible":true},{"url":"/r/NYKnicks/","visible":true},{"url":"/r/LosAngelesRams/","visible":true},{"url":"/r/steelers/","visible":true},{"url":"/r/nhl/","visible":true},{"url":"/r/FixedGearBicycle/","visible":true},{"url":"/r/fantasybaseball/","visible":true},{"url":"/r/Barca/","visible":true},{"url":"/r/denvernuggets/","visible":true},{"url":"/r/realmadrid/","visible":true},{"url":"/r/suns/","visible":true},{"url":"/r/NBASpurs/","visible":true},{"url":"/r/tampabayrays/","visible":true},{"url":"/r/peloton/","visible":true},{"url":"/r/AtlantaUnited/","visible":true},{"url":"/r/minnesotatwins/","visible":true},{"url":"/r/SanJoseSharks/","visible":true},{"url":"/r/Torontobluejays/","visible":true},{"url":"/r/ripcity/","visible":true},{"url":"/r/flyfishing/","visible":true},{"url":"/r/MCFC/","visible":true},{"url":"/r/balisong/","visible":true},{"url":"/r/redsox/","visible":true},{"url":"/r/LigaMX/","visible":true},{"url":"/r/phillies/","visible":true},{"url":"/r/NewYorkMets/","visible":true},{"url":"/r/SFGiants/","visible":true},{"url":"/r/ACMilan/","visible":true}]},{"title":"TV","links":[{"url":"/r/rupaulsdragrace/","visible":true},{"url":"/r/90DayFiance/","visible":true},{"url":"/r/dbz/","visible":true},{"url":"/r/Boruto/","visible":true},{"url":"/r/rickandmorty/","visible":true},{"url":"/r/howardstern/","visible":true},{"url":"/r/cordcutters/","visible":true},{"url":"/r/TheLastAirbender/","visible":true},{"url":"/r/IASIP/","visible":true},{"url":"/r/stevenuniverse/","visible":true},{"url":"/r/brooklynninenine/","visible":true},{"url":"/r/thebachelor/","visible":true},{"url":"/r/TheSimpsons/","visible":true},{"url":"/r/thewalkingdead/","visible":true},{"url":"/r/MtvChallenge/","visible":true},{"url":"/r/StrangerThings/","visible":true},{"url":"/r/survivor/","visible":true},{"url":"/r/thesopranos/","visible":true},{"url":"/r/batman/","visible":true},{"url":"/r/BravoRealHousewives/","visible":true},{"url":"/r/blackmirror/","visible":true},{"url":"/r/NetflixBestOf/","visible":true},{"url":"/r/Berserk/","visible":true},{"url":"/r/BlackClover/","visible":true},{"url":"/r/riverdale/","visible":true},{"url":"/r/BoJackHorseman/","visible":true},{"url":"/r/lucifer/","visible":true},{"url":"/r/TheBlackList/","visible":true},{"url":"/r/TeenMomOGandTeenMom2/","visible":true},{"url":"/r/overlord/","visible":true},{"url":"/r/trailerparkboys/","visible":true},{"url":"/r/BigBrother/","visible":true},{"url":"/r/PandR/","visible":true},{"url":"/r/community/","visible":true},{"url":"/r/adventuretime/","visible":true},{"url":"/r/Konosuba/","visible":true},{"url":"/r/fairytail/","visible":true},{"url":"/r/touhou/","visible":true},{"url":"/r/the100/","visible":true},{"url":"/r/scifi/","visible":true},{"url":"/r/titanfolk/","visible":true},{"url":"/r/TheHandmaidsTale/","visible":true},{"url":"/r/criterion/","visible":true},{"url":"/r/westworld/","visible":true},{"url":"/r/DanLeBatardShow/","visible":true},{"url":"/r/mylittlepony/","visible":true},{"url":"/r/Jeopardy/","visible":true},{"url":"/r/SpoiledDragRace/","visible":true},{"url":"/r/Gundam/","visible":true},{"url":"/r/MakingaMurderer/","visible":true},{"url":"/r/vanderpumprules/","visible":true},{"url":"/r/StarVStheForcesofEvil/","visible":true},{"url":"/r/anime_irl/","visible":true},{"url":"/r/TheDickShow/","visible":true},{"url":"/r/rpdrcringe/","visible":true},{"url":"/r/TheAmazingRace/","visible":true},{"url":"/r/LegendsOfTomorrow/","visible":true},{"url":"/r/marvelmemes/","visible":true},{"url":"/r/ImaginaryWesteros/","visible":true},{"url":"/r/HBOGameofThrones/","visible":true},{"url":"/r/GameOfThronesMemes/","visible":true},{"url":"/r/aSongOfMemesAndRage/","visible":true}]},{"title":"Travel","links":[{"url":"/r/vancouver/","visible":true},{"url":"/r/brasil/","visible":true},{"url":"/r/australia/","visible":true},{"url":"/r/mexico/","visible":true},{"url":"/r/argentina/","visible":true},{"url":"/r/ottawa/","visible":true},{"url":"/r/ireland/","visible":true},{"url":"/r/travel/","visible":true},{"url":"/r/Calgary/","visible":true},{"url":"/r/india/","visible":true},{"url":"/r/italy/","visible":true},{"url":"/r/AskNYC/","visible":true},{"url":"/r/europe/","visible":true},{"url":"/r/sydney/","visible":true},{"url":"/r/france/","visible":true},{"url":"/r/dubai/","visible":true},{"url":"/r/Edmonton/","visible":true},{"url":"/r/CasualUK/","visible":true},{"url":"/r/malaysia/","visible":true},{"url":"/r/askTO/","visible":true},{"url":"/r/JapanTravel/","visible":true},{"url":"/r/solotravel/","visible":true},{"url":"/r/newzealand/","visible":true},{"url":"/r/Turkey/","visible":true},{"url":"/r/Portland/","visible":true},{"url":"/r/thenetherlands/","visible":true},{"url":"/r/Atlanta/","visible":true},{"url":"/r/brisbane/","visible":true},{"url":"/r/halifax/","visible":true},{"url":"/r/chile/","visible":true},{"url":"/r/Winnipeg/","visible":true},{"url":"/r/japanlife/","visible":true},{"url":"/r/philadelphia/","visible":true},{"url":"/r/hungary/","visible":true},{"url":"/r/sandiego/","visible":true},{"url":"/r/Denver/","visible":true},{"url":"/r/Romania/","visible":true},{"url":"/r/translator/","visible":true},{"url":"/r/Dallas/","visible":true},{"url":"/r/Columbus/","visible":true},{"url":"/r/pittsburgh/","visible":true},{"url":"/r/berkeley/","visible":true},{"url":"/r/nashville/","visible":true},{"url":"/r/VictoriaBC/","visible":true},{"url":"/r/greece/","visible":true},{"url":"/r/WaltDisneyWorld/","visible":true},{"url":"/r/Austria/","visible":true},{"url":"/r/Sacramento/","visible":true},{"url":"/r/kansascity/","visible":true},{"url":"/r/croatia/","visible":true},{"url":"/r/sanfrancisco/","visible":true},{"url":"/r/vzla/","visible":true},{"url":"/r/Suomi/","visible":true},{"url":"/r/Denmark/","visible":true},{"url":"/r/orangecounty/","visible":true},{"url":"/r/nova/","visible":true},{"url":"/r/Minneapolis/","visible":true},{"url":"/r/saskatoon/","visible":true},{"url":"/r/SaltLakeCity/","visible":true},{"url":"/r/NewOrleans/","visible":true},{"url":"/r/Polska/","visible":true},{"url":"/r/Wellington/","visible":true},{"url":"/r/rva/","visible":true},{"url":"/r/Adelaide/","visible":true},{"url":"/r/brasilivre/","visible":true},{"url":"/r/Scotland/","visible":true},{"url":"/r/indonesia/","visible":true},{"url":"/r/IWantOut/","visible":true},{"url":"/r/serbia/","visible":true},{"url":"/r/rollercoasters/","visible":true},{"url":"/r/Detroit/","visible":true},{"url":"/r/sanantonio/","visible":true},{"url":"/r/Israel/","visible":true},{"url":"/r/Shoestring/","visible":true},{"url":"/r/podemos/","visible":true},{"url":"/r/newsokur/","visible":true},{"url":"/r/vagabond/","visible":true},{"url":"/r/TurkeyJerky/","visible":true},{"url":"/r/roadtrip/","visible":true},{"url":"/r/cirkeltrek/","visible":true}]},{"title":"Health & Fitness","links":[{"url":"/r/orangetheory/","visible":true},{"url":"/r/bodybuilding/","visible":true},{"url":"/r/bodyweightfitness/","visible":true},{"url":"/r/vegan/","visible":true},{"url":"/r/crossfit/","visible":true},{"url":"/r/nattyorjuice/","visible":true},{"url":"/r/loseit/","visible":true},{"url":"/r/xxfitness/","visible":true},{"url":"/r/powerlifting/","visible":true},{"url":"/r/1200isplenty/","visible":true},{"url":"/r/GetMotivated/","visible":true},{"url":"/r/intermittentfasting/","visible":true},{"url":"/r/CampingGear/","visible":true},{"url":"/r/skiing/","visible":true},{"url":"/r/leangains/","visible":true},{"url":"/r/progresspics/","visible":true},{"url":"/r/amateur_boxing/","visible":true},{"url":"/r/CampingandHiking/","visible":true},{"url":"/r/diabetes/","visible":true},{"url":"/r/Supplements/","visible":true},{"url":"/r/boostedboards/","visible":true},{"url":"/r/backpacking/","visible":true},{"url":"/r/camping/","visible":true},{"url":"/r/Stronglifts5x5/","visible":true},{"url":"/r/hiking/","visible":true},{"url":"/r/Brogress/","visible":true},{"url":"/r/migraine/","visible":true},{"url":"/r/C25K/","visible":true},{"url":"/r/HealthyFood/","visible":true},{"url":"/r/ehlersdanlos/","visible":true},{"url":"/r/swoleacceptance/","visible":true},{"url":"/r/EOOD/","visible":true},{"url":"/r/EDanonymemes/","visible":true},{"url":"/r/diabetes_t1/","visible":true},{"url":"/r/medical_advice/","visible":true}]},{"title":"Fashion","links":[{"url":"/r/MakeupAddiction/","visible":true},{"url":"/r/Watches/","visible":true},{"url":"/r/BeautyGuruChatter/","visible":true},{"url":"/r/frugalmalefashion/","visible":true},{"url":"/r/poshmark/","visible":true},{"url":"/r/tattoos/","visible":true},{"url":"/r/beards/","visible":true},{"url":"/r/goodyearwelt/","visible":true},{"url":"/r/Repsneakers/","visible":true},{"url":"/r/fragrance/","visible":true},{"url":"/r/LushCosmetics/","visible":true},{"url":"/r/malelivingspace/","visible":true},{"url":"/r/BeautyBoxes/","visible":true},{"url":"/r/beauty/","visible":true},{"url":"/r/Makeup/","visible":true},{"url":"/r/wicked_edge/","visible":true},{"url":"/r/rawdenim/","visible":true},{"url":"/r/RedditLaqueristas/","visible":true},{"url":"/r/Hair/","visible":true},{"url":"/r/Indiemakeupandmore/","visible":true},{"url":"/r/MUAontheCheap/","visible":true},{"url":"/r/Watchexchange/","visible":true},{"url":"/r/yeezys/","visible":true},{"url":"/r/streetwearstartup/","visible":true},{"url":"/r/findfashion/","visible":true},{"url":"/r/femalehairadvice/","visible":true},{"url":"/r/PanPorn/","visible":true},{"url":"/r/rolex/","visible":true},{"url":"/r/acne/","visible":true},{"url":"/r/Wetshaving/","visible":true},{"url":"/r/Youniqueamua/","visible":true},{"url":"/r/sneakermarket/","visible":true},{"url":"/r/SarahSnark/","visible":true},{"url":"/r/RepLadiesBST/","visible":true},{"url":"/r/makeupexchange/","visible":true}]}]}'),
		topicLinks: {},
	},
	shortcuts: { activeCommentId: null, activePostId: null, namespace: "Listing" },
	sidebarPromotedPosts: { firstFetch: false, models: {} },
	structuredStyles: {
		draft: {},
		exportStyles: { error: null, pending: false },
		flairTemplate: { models: {} },
		imagePreviews: {},
		isBladeEditorDirty: false,
		isEditing: null,
		models: {},
	},
	stylesheets: "https://www.redditstatic.com/desktop2x/chunkCSS/Reddit.401bac5158b118bca775_.css",
	subredditAutocomplete: { api: { error: {}, pending: {} }, models: {} },
	subreddits: {
		about: {},
		api: {
			about: { error: {}, pending: false },
			create: { error: { apiError: null }, lastCreatedSubredditId: null, initialCrosspost: null, pending: false },
			inlineEditing: { pending: false },
			models: { error: {}, pending: {} },
			onboarding: { pending: {} },
			productOffers: { error: null, pending: false },
			rankings: { error: null, pending: false },
			rules: false,
			settings: { pending: false },
			similar: { pending: {} },
			topContent: { error: {}, pending: {} },
			wiki: { error: {}, pending: {} },
		},
		appliedFilters: { meta: {} },
		byCategory: {},
		carousel: { pending: false, items: {} },
		communityInfo: {},
		countrySiteSettings: {},
		crosspostable: { api: { errors: null, pending: false }, ids: {} },
		duplicates: { models: {} },
		gov: { assets: {}, communityRaw: {}, distributions: {}, releaseNotes: {} },
		models: {} as Record<string, any>,
		moderated: { api: { errors: null, fetched: true, pending: false }, order: [] as string[] },
		notificationSettings: {},
		onboarding: {},
		powerupRecentSupporters: {},
		powerups: {},
		powerupsEmojis: {},
		productOffers: {},
		products: {},
		progressModule: {},
		questions: {},
		rankings: {},
		rankingsPageInfo: {},
		related: {},
		rules: {},
		settings: {},
		similar: {},
		mutedSubreddits: { ids: [], subreddits: [] },
		survey: {},
		topContent: {},
		trending: ["t5_36buk", "t5_3d7hf", "t5_2sxhs", "t5_gxikd"],
		unavailableModels: {},
	},
	subredditStickyPosts: { data: {} },
	subscriptions: {
		api: { errors: null, fetched: false, pending: false },
		favoriteMultiOrder: [],
		favoriteProfileOrder: [],
		favoriteSubredditOrder: [],
		multiredditOrder: [],
		profileOrder: [],
		subredditOrder: [],
	},
	survey: { activeDemoTrigger: null, demoTriggerThreshold: 1, isDemoEnabled: false, isSampleFactorEnabled: true, surveyNameCalledImmediately: "" },
	tabBadged: false,
	tags: {
		api: {
			create: { pending: false, error: false },
			deleteTag: { pending: false, error: false },
			fetch: { pending: false, error: false },
			update: { pending: false, error: false },
			updatePrimaryTag: { pending: false, error: false },
		},
		availableGlobalTagOrder: { global: [], recommendedGlobal: [] },
		models: {
			globalSubredditTags: {},
			subredditScopedTags: {},
			itemTags: {},
			geoPlaces: {},
			suggestedItemTags: {},
			sortedItemTags: {},
			subredditPrimaryTagId: {},
		},
		selected: {
			selectedPrimaryTagId: {},
			selectedOptions: {},
			selectedSuggestedOptions: {},
			deselectedOptions: {},
			deselectedSuggestedOptions: {},
			inputByItemId: {},
			suggestedInputByItemId: {},
		},
		creation: { selectedOptions: [], tagInput: "", selectedPrimaryTagId: null },
	},
	themes: {},
	toaster: [],
	tooltip: { params: null, tooltipId: null },
	tracing: {},
	tracking: { reCaptchaEnterprise: { load: 0, execute: 0, send: 0, reCaptchaEnterpriseToken: "" }, viewportDataLoaded: {} },
	trafficStats: { pending: false, trafficStats: null },
	transfers: { communityPoints: { api: { error: null, pending: false }, contentId: null, initialRecipient: "", publicAddress: null } },
	trending: { models: {} },
	trophies: {},
	uploads: {},
	user: {
		account: null as null | Record<string, any>,
		accountSettings: { changeEmail: { api: { error: null, pending: false } }, sendResetEmail: { api: { pending: false, emailSent: false } } },
		blocked: {
			api: {},
			data: [],
		},
		chatSettings: { invitePolicy: "Everyone" },
		drafts: null,
		experiments: {
			byName: experiments,
			localPersisted: {},
		},
		isCustomizeFlyoutShowing: false,
		topContentDismissalPrefsSet: {},
		language: "en",
		loid: {
			blob: "Z0FBQUFBQm1EcmlSMWg0OV92a0M5WmVTWXpQUERaZERQV3lIYTh6djV0U1BEWUVIckc1S3JaOGJ0bnJ2eTY1QjloODVGR0dHZHZzOS1GRVYwSWJyOGZ4N2NDMHAtWmlYdlZkcXVCRG9CZnJTTzlSMmdjVzdhc3RMdXpEcy05NVdTNlUyTTg1VkNWaWI",
			loid: "0000000000k4vwrnsy",
			loidCreated: "1645962995000",
			version: 2,
		},
		notificationPrefs: {
			api: { getPreferences: { error: null, loaded: false, pending: false }, setPreferences: { error: null, loaded: false, pending: false } },
			subscribedSubredditsSettings: { subreddits: [], pageInfo: null },
			emailSettingsLayout: { sections: { byId: {}, allIds: [] }, rows: { byId: {}, allIds: [] } },
			isAskNotificationPromptVisible: false,
			isNotificationPromptVisible: false,
			preferences: {
				broadcastFollower: false,
				broadcastRecommendation: false,
				chatMessages: false,
				chatRequests: false,
				commentReplies: false,
				communityRecommendations: false,
				liveEvent: false,
				newPinnedPost: false,
				postFlairAdded: false,
				postReplies: false,
				privateMessages: false,
				threadReplies: false,
				topLevelComment: false,
				trendingPosts: false,
				upvotedComments: false,
				upvotedPosts: false,
				userFlairAdded: false,
				usernameMentions: false,
				userNewFollowers: false,
			},
			pushSettingsLayout: { sections: { byId: {}, allIds: [] }, rows: { byId: {}, allIds: [] } },
		},
		ownedBadges: {},
		powerups: { data: null, fetched: false },
		prefs: {
			acceptPrivateMessages: "everyone",
			activityRelevantAds: false,
			allowClickTracking: false,
			autoplayVideo: false,
			badCommentAutocollapse: "OFF",
			collapsedTraySections: { favorites: false, multis: true, moderating: true, subscriptions: false, profiles: false },
			collapseReadMessages: false,
			commentMode: "markdown",
			countryCode: "XZ",
			defaultCommentSort: "confidence",
			editorMode: "markdown",
			emailDigests: false,
			emailUnreadMessages: false,
			emailUnsubscribe: true,
			enableFollowers: true,
			gatedSubredditOptIn: false,
			geopopular: "",
			globalTheme: "REDDIT",
			hasSeenCustomizeFlyout: true,
			hideAds: true,
			hideFromRobots: false,
			hideNSFW: false,
			highlightComments: true,
			ignoreSuggestedSort: false,
			isAdPersonalizationAllowed: true,
			isFirstPartyAdPersonalizationPreferenceShown: true,
			isThirdPartyAdPersonalizationAllowed: true,
			isThirdPartyInfoAdPersonalizationAllowed: true,
			isThirdPartySiteAdPersonalizationAllowed: true,
			labelNSFW: true,
			layout: "card",
			liveBarRecommendationsEnabled: false,
			loginOtpEnabled: false,
			markMessagesRead: false,
			nightmode: true,
			openPostInNewTab: false,
			over18: true,
			quarantineOptIn: false,
			reduceAnimationsFromAwards: false,
			rememberCommunityLayout: true,
			rememberCommunitySort: true,
			searchOver18: true,
			sendWelcomeMessages: true,
			sensitiveAdsPreferences: {
				isAlcoholAllowed: true,
				isDatingAllowed: true,
				isGamblingAllowed: true,
				isPregnancyAndParentingAllowed: true,
				isWeightLossAllowed: true,
			},
			showActiveCommunities: true,
			showMessagesInInbox: true,
			showNotifications: true,
			showPresence: true,
			showTwitter: false,
			showUsernameMentionNotifications: true,
			sort: "hot",
			stylesEnabled: true,
			subreddit: {},
			subscriptionsPinned: false,
			thirdPartyDataPersonalizedAds: false,
			thirdPartyPersonalizedAds: false,
			thirdPartySiteDataPersonalizedAds: false,
			thirdPartySiteDataPersonalizedContent: false,
			topContentDismissalTime: null,
			topContentTimesDismissed: 0,
			useMarkdown: true,
		},
		productOfferSubscriptions: { status: "default", subscriptions: [] },
		session: {
			accessToken:
				"eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzIwODcyODg5LjE1MDg4NywiaWF0IjoxNzIwNzg2NDg5LjE1MDg4NywianRpIjoiXy1PNkIwamtEVjdNTDNOaUpEWHVKTkxTOTFGeDRnIiwiY2lkIjoiOXRMb0Ywc29wNVJKZ0EiLCJsaWQiOiJ0Ml9rNHZ3cm5zeSIsImFpZCI6InQyX2s0dndybnN5IiwibGNhIjoxNjQ1OTYyOTk1MDAwLCJzY3AiOiJlSnhra2RHT3REQUloZC1sMXo3Ql95cF9OaHRzY1lhc0xRYW9rM243RFZvY2s3MDdjTDRpSFA4bktJcUZMRTJ1QktHa0tXRUZXdE9VTmlMdjU4eTlPWkVGU3lGVFI4NDN5d29rYVVwUFVtTjVweWxSd1daa0xsZmFzVUtEQjZZcFZTNloyMEtQUzV2UTNJMUZ6MDZNcWx4V0h0VFlvM0pwYkdNSzJ4UGp6Y1pxUXlxdXk2bE1ZRmtvbjhXTGZ2eUctdFktZjdiZmhIWXdyS2dLRF9UT3VGeHdZX0hERkhiX25wcjBiRjJ3cUwzWGc5US0xLU4yN2JObW9kbTVfVnpQdnphU2NUbUc1aWZZdjd0LUNSMTQ1SG1aVVFjd1lnMF95ckFqNl9Ddk9vREtCUVdNSlloUEk1QXJsMl9fSmRpdVRmOGF0eWQtLUdiRVRXXzRyUm1vNXhMRW9VX2o2emNBQVBfX1hEX2U0dyIsInJjaWQiOiIzZm14Z1k5NWpBd2oxYll2Q080VG9DTHliTGNZTmxOb0dhYVlzSWNyNE4wIiwiZmxvIjoyfQ.f-8XvPPgbnUZc-DY-gdHVeYw6wvabkN8fa_tNzlSQTMVB2x9IJW30vZVUqyP4LMDUDjWjlESEYE7ZQPg5qR0o0hv-eJcQkzopVY0vgRZF6B2GKCupxpm1Gitfxsh0LWAcF0tyZPV0Hvs8BP-mox9e-oQ0eziVe63kjUETskyQY4Ez1VLahExe7024c_qtx_WgmTNR5CwZcDF2bcUwOI2m9aYRopx79M0PAEx3QdUo4U81NGu33_0RZcJPDdiV6ts5P-bAaqpoSAY_IONmqNm6Vc8_T6Vy0Nu00FWZBtf9y64heLn8SLThf-vTflqLWnEPvrWfGbNjnjNWpdWAJimXA",
			expires: "2024-07-13T12:14:49.000Z",
			expiresIn: 86257054,
			unsafeLoggedOut: false,
			safe: true,
		},
		sessionRefreshFailed: false,
		sessionTracker:
			"ilnlormajjbpdgmpff.0.1720786631922.Z0FBQUFBQm1rUjdIRGYwVnVpdXJYSDZQVzFSR21jb2dNTi1CcVpQbzZDUlVjNlNGc1FnSnhLaVpTSS1oTmJ2MGJvTjdSV3RadW1aMzNWYS1mODZmWEFpNC1VVGhOLVBJSXFsRDYtdTZtQzYtMFJMcmdETVpRb1IxUElZUUdNZV9lNHp2T0s1bFVpcmE",
		temporaryGQL: { isEmployee: false, isLoggedIn: true },
		wallets: {},
		whitelist: {
			api: {},
			data: [],
		},
	},
	userDataRequestPage: { userDataRequestPageApi: { error: null, pending: false, success: false, userDataExportEligibility: false } },
	upvotePromptCountPerSess: 0,
	users: {
		api: { error: {}, pending: false },
		appliedBadges: {},
		models: {},
		nameAvailable: {},
		topAwarders: { api: { error: null, pending: false }, currentPostId: null, currentRank: {}, list: {} },
		powerups: { fetched: false },
	},
	widgets: { idCardIds: {}, menuIds: {}, models: {}, moderatorIds: {}, sidebar: {} },
	features: {
		removalReasons: { api: { error: null, pending: false }, models: {}, reasonOrder: {}, removedItemIds: null },
		realtimeUpdateAnimationId: null,
		powerupsBenefitSettings: {},
		modActivitySummaries: {},
		eligibleUXExperiences: { experiences: {} },
		devPlatform: { formModal: { form: null, onSubmit: null }, userInputModal: { action: null, onAction: null } },
		activeCommunitiesOnProfile: {},
		matrixChat: { state: 0, url: "https://chat.reddit.com" },
		crypto: { claims: {}, points: {}, publicWallets: {} },
		happeningNow: {
			api: { error: null, loaded: false, pending: false },
			models: {},
			popular: [],
			recommended: [],
			selectedFilter: "all",
			showLiveContentAvailabilityTooltip: false,
			unread: { lastReadTimestampMs: 0, latestUnreadContentTimestampMs: 0 },
		},
		communityChat: { selectedChannelId: "", models: {}, channelIds: {}, hasShownToastMessage: false },
		categories: {
			api: { list: { error: null, loaded: false, pending: false }, subreddits: { error: {}, loaded: {}, pending: {} } },
			ids: [],
			models: {},
			nameToId: {},
			ranking: {},
		},
		powerups: { subredditPowerupsFlairs: {}, subredditUserPowerupsFlairs: {} },
		socialLinks: {},
		marketplace: { feedUnit: { id: null, title: "", description: "", buttonCtaText: "", feedIndex: 0 }, claimStatus: {}, linkPreview: {} },
		predictions: {
			creation: [],
			leaderboards: {},
			tournaments: {},
			tournamentsLeaderboards: {},
			tournamentsBySubreddit: {},
			queriedLeaderboards: {},
		},
		comments: {
			collapsed: {},
			drafts: {},
			focused: {},
			hidden: {},
			isEditing: {},
			models: {} as Record<string, any>,
			replyFormOpen: {},
			submit: { error: {}, pending: {} },
			visitHighlightFilter: "Last",
		},
		goldPurchase: {
			packageOfferModal: { packageId: null },
			payment: {
				cardName: "",
				cardValidation: { cardCvc: "", cardExpiry: "", cardNumber: "", nameOnCard: "", postalCode: "" },
				paymentMethod: null,
				paypal: { errorMessage: null, passthrough: "" },
				postalCode: "",
				rememberCard: true,
				savedCards: [],
				savedCardsPending: false,
				stripeToken: { errorMessage: null, pending: false },
				useSavedCard: null,
			},
			premiumPurchaseModal: { activePage: "selectPayment", showModal: false, packageId: null, renewInterval: null },
			productOffers: {},
			purchaseCatalog: {
				activeSaleConfig: null,
				api: { errorMessage: null, recommendedPending: false, storefrontPending: false },
				coinPackages: { models: {}, dealPackageIds: [], recommendedPackageIds: [], storefrontPackageIds: [] },
				freeAwardEvent: null,
				premiumPackages: [],
			},
			purchaseModal: { activePage: "selectPayment", correlationId: null, gildThingId: null, packageId: null, showModal: false },
		},
		modUserNotes: {
			api: { error: null, pending: {} },
			fetchedTokens: {},
			lastAuthorModNotes: {},
			loadMore: {},
			models: {},
			order: {},
			totalCount: {},
		},
		userFlair: {} as Record<string, any>,
		shouldTryToShowCrosspostModal: false,
		avatar: {
			marketing: null,
			avatarUser: {
				id: "",
				csrf_token: "",
				snoovatar: null,
				websocketsUrls: { renderer: "", download: "" },
				capabilities: ["PREMIUM"],
				hasActiveClosetSubscription: false,
			},
			randomAvatar: null,
		},
		creatorStats: { postOtherDiscussions: {}, postStats: {}, subredditKarma: {} },
		banned: {
			api: { error: null, pending: {} },
			fetchedTokens: {},
			inContext: null,
			loadMore: {},
			models: {},
			search: { api: { error: null, pending: false }, result: null },
			userOrder: {},
		},
		econPurchase: { subredditLockedCoins: {} },
		liveBar: { items: [] },
		modPreviousActions: { models: {}, order: {} },
		realtimeModqueue: { toUpdate: [], updated: [] },
		relatedCommunitiesRecommendations: {},
		reportFlow: {
			api: { error: {}, pending: {}, success: {} },
			openedFromModalPage: false,
			postOrCommentId: null,
			userIsMod: false,
			rulesCategory: null,
		},
	},
};

export const hydrateState = () => Promise.all([
	addUserRels(state),
	addIdentityToState(state),
	addPrefsV1ToState(state),
]);

export let isLoggedIn = {
	value: false,
};