import { getLogger } from "./logging";
import { initAPIMigratorInterceptors } from "./apiMigrate";
import { gqlFetch } from "./api/gql";
import experiments from "./state/experiments.json";
import { getLoidState } from "./state/utils";

const logger = getLogger('init');

logger.dbg("Initializing client...");
window.clientLoaded = false;


export const userscriptLoaded = ((): Promise<void> => {
	if (window.__MODREDDITCOM_REVIVED__) {
		return Promise.resolve();
	}

	return new Promise((resolve) => {
		window.addEventListener("rAPI-accessToken-ready", () => resolve(), { once: true });
	});
})();

export const initialState = {
	pages: {
		profileOverview: {
			chrono: { api: { error: {}, pending: {} }, fetchedTokens: {}, ids: {}, loadMore: {} },
			conversations: {
				api: { error: {}, pending: {} },
				extraComments: { api: { error: {}, pending: {} }, models: {} },
				keyToCommentThreadLinkSets: {},
				keyToHeadCommentId: {},
				keyToPostId: {},
			},
		},
		modHub: {
			approvedSubmitters: {
				api: { error: null, pending: {} },
				fetchedTokens: {},
				loadMore: {},
				models: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: {},
			},
			approvedTalkHosts: { api: { error: null, pending: {} }, fetchedTokens: {}, loadMore: {}, models: {} },
			flairedUsers: {
				api: { error: null, pending: false },
				models: {},
				pageInfo: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: {},
			},
			moderationLog: {
				actionCategories: {},
				actions: { itemOrder: {}, models: {} },
				approximateCount: null,
				endCursor: null,
				hasNextPage: {},
				hasPreviousPage: {},
				moderators: [],
				startCursor: null,
				insightsEntrypoint: null,
			},
			moderators: {
				editableModerators: {},
				editableUserOrder: { data: {}, api: { error: {}, pending: {} } },
				invitedModerators: { api: { error: null, pending: false }, models: {}, userOrder: {} },
				invitePending: {},
				loadMoreModerators: {},
				loadMoreEditableModerators: {},
				models: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: { data: {}, api: { error: {}, pending: {} } },
			},
			modQueue: {
				bulkAction: { api: { error: null, pending: false }, selectedItems: {}, undoLastAction: {} },
				edited: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				moderatedCommunitiesOrder: { after: null, data: [], loaded: false, pending: false },
				modqueue: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				reports: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				spam: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
				unmoderated: { api: { error: null, pending: false }, itemOrder: {}, loadMore: {} },
			},
			muted: {
				api: { error: null, pending: {} },
				fetchedTokens: {},
				inContext: null,
				loadMore: {},
				models: {},
				search: { api: { error: null, pending: false }, result: null },
				userOrder: {},
			},
		},
		comments: {
			api: { error: {}, fullyLoaded: {}, pending: {} },
			followed: [],
			keyToChatCommentLinks: {},
			keyToCommentThreadLinkSets: {},
			keyToHeadCommentId: {},
			keyToPostId: {},
			ads: [],
		},
		topics: { models: {} },
		econManagement: { displayState: "default", currentEntity: null, relatedData: {}, entityTypes: {} },
		followers: { api: { pending: false }, models: {}, pageInfo: null, search: {}, userIds: [] },
		subredditWiki: {
			diff: {},
			directory: {},
			pages: {},
			pageSettings: {},
			revisions: { api: { error: {}, pending: {} }, listings: {}, models: {} },
			wikiBannedContributors: { listing: { afterToken: {}, api: { error: {}, pending: {} }, models: {}, userOrder: {} }, search: {} },
			wikiContributors: { listing: { afterToken: {}, api: { error: {}, pending: {} }, models: {}, userOrder: {} }, search: {} },
		},
	},
	accountManagerModalData: {},
	activeModal: null,
	ads: {},
	adsSignals: { adsSeenCount: 0, totalPostsSeenCount: 0, sessionStartTime: new Date().toISOString() },
	apiRequestState: {},
	appBadges: { api: { error: null, pending: false }, badges: {} },
	authorFlair: { inContext: null, models: {} },
	awards: {
		blacklist: {},
		create: { api: { error: null, pending: false } },
		manageable: { api: { error: null, pending: {} }, availability: {}, order: {} },
		models: {
			gid_1: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 100,
				coinReward: 0,
				description: "Shows the Silver Award... and that's it.",
				daysOfDripExtension: 0,
				icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-silver-medium.png?v=2" },
				staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-silver-medium.png?v=2" },
				id: "gid_1",
				isEnabled: true,
				isNew: false,
				name: "Silver",
				daysOfPremium: 0,
				tiers: null,
			},
			gid_2: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 500,
				coinReward: 100,
				description: "Gives 100 Reddit Coins and a week of r/lounge access and ad-free browsing.",
				daysOfDripExtension: 0,
				icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
				staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
				id: "gid_2",
				isEnabled: true,
				isNew: false,
				name: "Gold",
				daysOfPremium: 7,
				tiers: null,
			},
			gid_3: {
				awardType: "GLOBAL",
				awardSubType: "GLOBAL",
				coinPrice: 1800,
				coinReward: 0,
				description:
					"Gives a month of free Premium, which includes ad-free browsing, r/lounge access, and 700 Reddit Coins per month, until Coins are sunset on September 12, 2023.",
				daysOfDripExtension: 31,
				icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-platinum-medium.png?v=2" },
				staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-platinum-medium.png?v=2" },
				id: "gid_3",
				isEnabled: true,
				isNew: false,
				name: "Platinum",
				daysOfPremium: 31,
				tiers: null,
			},
		},
		sortedUsable: { api: { pending: {} }, order: {} },
		tags: { order: {} },
		chatReactions: { availability: {}, pending: {} },
	},
	badges: { api: { subreddit: { error: {}, pending: {} }, user: { error: {}, pending: {} } }, models: {} },
	blockedRedditors: { api: { error: { message: "" }, pending: false }, list: { ids: [] } },
	blockUser: { api: { error: {}, pending: {} } },
	brandSafety: { isViewSafe: true, hasBrandSafetyBeenAssessed: false },
	chat: { liveChatTooltipShowState: "never_shown", showChatChannelDiscoveryTooltip: false, activeUserCountByLiveChatId: {}, hasSendbirdChats: null },
	commentsListTruncated: true,
	communityFlairs: {},
	connection: { showBanner: false, online: true },
	contentControls: { api: { fetch: { error: {}, pending: {} } }, models: {} },
	contentGate: {},
	continueThreads: { models: {} },
	creations: {
		api: {
			collection: { createOrUpdate: { error: null, pending: false } },
			draft: {
				deleteDraft: { error: {}, pending: {} },
				listing: { error: null, pending: false },
				save: { error: { apiError: null, needsCaptcha: false, validationError: null, submitValidationError: null }, pending: false },
			},
			editor: { converting: { pending: {} }, mediaUpload: { error: null, pending: false } },
			page: { error: {}, fetched: {}, pending: {} },
			post: {
				submit: { error: { apiError: null, needsCaptcha: false, validationError: null, submitValidationError: null }, pending: false },
				update: { error: null, pending: false },
			},
			subreddit: { change: { error: null, pending: false } },
		},
		drafts: {},
		formData: {
			body: {
				link: "",
				markdown: "",
				media: { items: [], selectedKey: null },
				rte: { isBound: false, editorKey: "7b044e", initialRTJSON: { document: [] } },
			},
			eventSchedule: null,
			flair: null,
			govType: null,
			isChatPost: false,
			isContestMode: false,
			isNSFW: false,
			isOC: false,
			isPostAsMetaMod: false,
			isPoll: false,
			isPublicLink: false,
			isSpoiler: false,
			newSubreddit: "",
			newTopMod: "",
			nextSubreddit: null,
			polls: null,
			postSchedule: null,
			postToTwitter: false,
			recaptcha: "",
			scheduledPostId: null,
			sendReplies: true,
			stickyPosition: null,
			submissionType: "post",
			suggestedSort: null,
			title: "",
			tournament: { name: "", theme: "theme_1", token: null },
			talk: { theme: "periwinkle", topics: [], isUpcoming: false },
		},
		formState: {
			editorMode: null,
			fieldValidation: { title: [], body: [], link: [], flair: [] },
			isChanged: false,
			submitMode: 0,
			postGuidance: { uniqueRules: [], titleTriggeredRules: [], bodyTriggeredRules: [], isBlockRuleTriggered: false, errors: null },
		},
		postEditing: { draft: { markdown: "", rte: { isBound: false, editorKey: "6b9bed", initialRTJSON: { document: [] } } }, postId: null },
		subredditRec: { api: { error: false, pending: false }, isInputChanged: false, model: {}, order: [] },
	},
	dashboard: { selectedComponent: null, subredditPending: false, subredditLoaded: {} },
	discoveryUnits: { api: { list: { error: null, loaded: false, pending: false } }, models: {}, nameToId: {} },
	dismissedTruncationList: [],
	economics: {
		banners: { dismissedBanners: {} },
		currentBadgeManagementScreen: { badgeType: "cosmetic", view: "gallery" },
		currentModalArgs: null,
		emotes: {},
		gifs: {},
		me: { fetched: false, data: {} },
		paymentSystems: { status: 2 },
		pointsCopy: { fetched: false, data: null },
		subredditPremium: {},
	},
	emailVerificationTooltip: { isShowing: false },
	emojis: { api: { list: { pending: {} } }, models: {} },
	experimentOverrides: {},
	externalAccount: {
		api: {
			connect: { error: {}, pending: {} },
			disconnect: { error: {}, pending: {} },
			user: { error: {}, pending: {} },
			subreddit: { error: {}, fetched: {}, pending: {} },
		},
		user: {},
		subreddit: {},
	},
	featureFlags: {
		overrides: {
			introModal: null,
			markdownMode: null,
			modQueue: null,
			spBadges: null,
			spBurnLinks: null,
			spClaimablePoints: null,
			spCustomBadgesAndEmotes: null,
			spCustomCrypto: null,
			spEmotes: null,
			spGiphy: null,
			spGovPolls: null,
			spHarberger: null,
			spLeaderboard: null,
			spPoints: null,
			spPointsCoinConversion: null,
			spPolls: null,
			spPublicPoints: null,
			spSpecialMemberships: null,
			spSpecialMembershipUpsells: null,
			spSpinoffs: null,
			spTipping: null,
			spWalletRegistrationBanner: null,
			scheduledPosts: null,
			adminCommunityTopics: null,
			rteVideoPoster: null,
			devAndStagingWatermark: true,
			fpsMeter: true,
			rabbitHole: null,
			measureScrollFPS: null,
			showVerboseErrors: true,
			srAdoptionWeek: null,
			uappBanner: null,
			experiments: null,
			enableGraphQl: null,
			importExportThemes: null,
			flairRestrictions: null,
			newPostRequirements: null,
			superbOwl: null,
			enableShadowMode: null,
			pushNotificationsBrowserSupported: null,
			enableToxicityWarning: null,
			snoovatar30: null,
			geoSubredditRecommendationDULoggedIn: null,
			geoSubredditRecommendationDULoggedOut: null,
			subredditInlineEditing: true,
			modToMemberShare: null,
			subredditMentionD2xExperiment: null,
			reCaptchaEnterprise: false,
			hatefulContentFiltersEnabled: null,
			__requiredDoNotRemove: null,
		},
	},
	firstPost: {
		currentPromptIndex: 0,
		firstFormEditEvent: false,
		postBody: "",
		postSubmitted: false,
		postTitle: "",
		selectedPredicatesInt: [],
		subreddit: { subredditId: "", subredditName: "" },
	},
	focusedVerticals: {
		api: { error: { focusedVerticalGqlError: null }, pending: { focusedVerticalGqlPending: false } },
		components: { dismissed: true },
		interactedSubredditIds: null,
		recommendedSubredditIds: null,
		category: "",
		lastLoadedEnv: null,
	},
	fontFiles: [],
	frontPageFirstLoaded: true,
	gild: {
		api: { error: null, pending: false, showLoader: false },
		correlationId: null,
		gildModalThingId: null,
		isAnonymous: false,
		isIframed: false,
		message: "",
		gildedThing: null,
		selectedAward: {
			awardType: "GLOBAL",
			awardSubType: "GLOBAL",
			coinPrice: 500,
			coinReward: 100,
			description: "Gives 100 Reddit Coins and a week of r/lounge access and ad-free browsing.",
			daysOfDripExtension: 0,
			icon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
			staticIcon: { url: "https://www.redditstatic.com/desktop2x/img/gold/badges/award-gold-medium.png?v=2" },
			id: "gid_2",
			isEnabled: true,
			isNew: false,
			name: "Gold",
			daysOfPremium: 7,
			tiers: null,
		},
	},
	header: { isSubscriptionsDropdownOpen: false },
	htmlResponseStreaming: true,
	imageUploads: {},
	impressionMap: {},
	interceptedAction: null,
	isChangeUsernameTooltipShowing: true,
	isModeratorWithPostPerms: false,
	jsApi: [],
	langSite: { bannerClosedTime: 0 },
	leaderboard: { api: { error: {}, pending: {} }, models: {} },
	listings: {
		activeKey: null,
		authorOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		commentOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		communityOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		listingOrder: { api: { error: {}, pending: {} }, identifiers: {}, fetchedTokens: {}, loadMore: {} },
		postOrder: {
			api: { error: {}, pending: {} },
			correlationIds: {},
			endMarkers: {},
			fetchedTokens: {},
			ids: {},
			listingSort: {},
			loadMore: {},
			pageInfo: {},
			treatment: {},
		},
	},
	live: { announcements: null, featured: null, isFrontpageLoaded: true, shouldShowAnnouncements: false },
	mediaEmbed: {},
	mediaGalleries: { currentSlideIndex: {}, isGalleryTileLayout: {} },
	mediaPlayback: { isMuted: true, volume: 0.5 },
	merchandisingUnitAnnouncements: [],
	meta: {
		country: "AU",
		region: "NSW",
		city: "Hamilton",
		domain: "www.reddit.com",
		isBot: false,
		isLikelyMod: true,
		isSessionSeo: false,
		method: "GET",
		platform: {
			osName: "windows",
			osVersion: "10",
			browserName: "edge",
			browserVersion: "127-0-0-0",
			primaryLanguage: "en-GB",
			languageList: "en-GB,en;q=0.9,en-US;q=0.8",
		},
		protocol: "https",
		sessionReferrerDomain: "",
		userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0",
		isOneTapSession: false,
		locale: "en-US",
		pageloadServerTime: 1720786631931,
		samplingBucket: 29.9,
		edgebucket: "yHSvZtREODvfTOTEgn",
	},
	moderatingSubreddits: {},
	modListingPage: { filteredSubreddits: { api: { error: null, pending: false }, names: [] } },
	modModeEnabled: true,
	moreComments: { api: { error: {}, pending: {} }, models: {} },
	multireddits: {
		api: {
			addSubreddit: { error: null, fetched: false, pending: null },
			create: { error: null, fetched: false, pending: false },
			deleteMulti: { error: null, fetched: false, pending: false },
			duplicate: { error: null, fetched: false, pending: false },
			edit: { error: null, fetched: false, pending: false },
			forUser: { fetched: false, pending: false },
			recommendations: { error: null, fetched: false, pending: true },
			removeSubreddit: { error: null, fetched: false, pending: null },
		},
		byUserId: {},
		models: {},
		recommendations: {},
	},
	notificationBannerId: null,
	inactiveModeratorError: false,
	notificationsInbox: {
		api: { error: false, pending: false },
		banner: { banners: [], dismissedBanners: [] },
		earlierDividerIndex: null,
		notifications: [],
		pageInfo: null,
		markAllAsReadTimestamp: null,
	},
	nps: { pending: false, success: false },
	onboarding: { genderUpdateState: { success: false, failure: false }, interestTopicRecommendationsState: null, shouldSkipOnboardingState: false },
	page: {
		experiments: {
			byName: {
				seo_image_descriptive_filenames: { id: 4525, name: "seo_image_descriptive_filenames", variant: "control_1", version: "21" },
				indexing_api_mod_approvals: { id: 5199, name: "indexing_api_mod_approvals", variant: "variant_1", version: "7" },
				seo_indexing_deletes_migration: { id: 7204, name: "seo_indexing_deletes_migration", variant: "enabled", version: "3" },
				seo_indexing_drop_auto_removed: { id: 7912, name: "seo_indexing_drop_auto_removed", variant: "enabled", version: "3" },
				seo_indexing_creates_migration: { id: 8045, name: "seo_indexing_creates_migration", variant: "enabled", version: "3" },
				seo_indexing_updates_migration: { id: 8204, name: "seo_indexing_updates_migration", variant: "enabled", version: "3" },
				shreddit_media_post_link_preview: { id: 8457, name: "shreddit_media_post_link_preview", variant: "enabled", version: "6" },
				shreddit_cdn_media_page_domain_redirect: { id: 8690, name: "shreddit_cdn_media_page_domain_redirect", variant: "enabled", version: "25" },
				seo_mweb3x_bot_footer_inline_styles: { id: 10665, name: "seo_mweb3x_bot_footer_inline_styles", variant: "enabled", version: "4" },
				seo_mt_links: { id: 11267, name: "seo_mt_links", variant: "enabled", version: "8" },
				seo_klp_recommendations: { id: 11330, name: "seo_klp_recommendations", variant: "enabled", version: "7" },
				seo_klp_semantic_recommendations: { id: 11331, name: "seo_klp_semantic_recommendations", variant: "enabled", version: "11" },
				seo_klp_local_klp_store_deprecation: { id: 12925, name: "seo_klp_local_klp_store_deprecation", variant: "enabled", version: "10" },
				i18n_translation_llm_provider: { id: 13258, name: "i18n_translation_llm_provider", variant: "gemini15flash", version: "3" },
				i18n_proactive_translation_indexing: { id: 13638, name: "i18n_proactive_translation_indexing", variant: "control_1", version: "3" },
			},
			canonicalUrl: "https://www.reddit.com/",
		},
	},
	platform: {
		allowNavigationCallback: null,
		currentPage: {
			key: "/",
			locationState: { feedCorrelationId: "b3b8d516-d7d3-47cf-80a2-32908efddf7e" },
			meta: { name: "index", pageType: "home", canonicalPageType: "home" },
			queryParams: {},
			routeMatch: {
				match: { path: "/", url: "/", isExact: true, params: {}, queryParams: {} },
				route: {
					chunk: "Frontpage",
					component: {},
					exact: true,
					prefetches: ["CommentsPage", "Subreddit"],
					path: "/",
					meta: { name: "index", pageType: "home", canonicalPageType: "home" },
				},
			},
			status: 200,
			url: "/",
			urlParams: {},
		},
		lastPage: null,
		referrers: {},
		sessionReferrer: null,
		metas: { "/": { title: "Reddit - Dive into anything" } },
	},
	postCollection: {
		models: {},
		subredditToIds: {},
		api: {
			error: { reorderError: null, updateDescriptionError: null, updateLayoutError: null },
			pending: { reorderPending: false, updateDescriptionPending: false, updateLayoutPending: false },
		},
	},
	polls: { api: { voting: { error: {}, pending: {} } }, models: {}, results: { byVoters: {}, byVotingPower: {} }, rewards: {} },
	postFlair: {},
	posts: {
		embedAndImage: { loadable: {} },
		expanded: {},
		focus: null,
		followed: [],
		instances: {},
		isAnimatingUpvote: null,
		isTrackingCrossposts: {},
		metaMap: {},
		models: {},
		modToMemberShare: null,
		crowdControl: null,
		postLevelCrowdControl: {},
		recent: [],
		scheduledPosts: {
			api: { creationToken: "b5a6b6c2-57fe-402b-bce4-c6099c650459", error: null, pending: true, pendingUpdate: false },
			standalonePosts: { models: {}, pageInfo: {}, postOrder: {} },
			recurringPosts: { models: {}, pageInfo: {}, postOrder: {}, editModal: {} },
		},
		topAwarded: { api: { error: null, pending: false }, list: [] },
		video: {
			autoPlayed: {},
			buffering: {},
			consumed: {},
			continuousViewStartedAt: {},
			feed: { mutedInFeed: true },
			fullscreen: null,
			loadable: {},
			loadTimes: {},
			metadata: {},
			paused: {},
			playing: {},
			started: {},
			time: {},
		},
		carousel: { pending: false, items: {} },
	},
	postGuidance: { api: { fetch: { error: {}, pending: {} } }, models: {}, allowlist: {} },
	postStickiedComments: { data: {} },
	givePremium: { api: { error: null, pending: false }, givePremiumModalAccountName: "" },
	products: { api: { fetch: { error: {}, pending: {} }, purchase: { error: {}, pending: {} } }, currentlyPurchasing: null, models: {} },
	profileCommentsPage: { api: { error: {}, pending: {} }, endMarkers: {}, fetchedTokens: {}, commentIds: {}, loadMore: {} },
	profilePrivatePage: { api: { error: {}, pending: {} }, ids: {}, pageInfo: {} },
	profileModSettingsPage: { api: { pending: true } },
	profilePostsPage: {},
	profiles: {
		about: {},
		models: {},
		moderated: { api: { pending: {} }, models: {}, pageInfo: {} },
		multireddits: { api: { pending: {} }, pageInfo: {} },
		pinnedPosts: { data: {}, initialData: {}, pending: {} },
		trophyCases: {},
	},
	promos: { mobilePromoBanner: false, upsellSignUpBannerLarge: false, upsellSignUpBannerMedium: false, upsellSignUpBannerSmall: null },
	recap: {
		isImageLoading: false,
		isCardsLoading: true,
		cardsLoadingError: null,
		cards: [],
		shareCardWasOpened: false,
		currentCardIndex: 0,
		bannerSeen: true,
		shouldShowShareModal: false,
		shouldHideAbilityCardUsername: false,
		shouldHideAbilityCardAvatar: false,
	},
	recentSubreddits: [],
	recommendations: {},
	reportPage: { reportPageApi: { error: null, pending: false, success: false }, reportPageRules: [], initialReason: null },
	reportRules: { sitewideRules: [] },
	requestHost: "reddit-desktop-external.kubernetes.ue1.snooguts.net",
	runTimeEnvVars: { staging: true, startTimeInMillis: 1720534529852 },
	search: {
		appliedSort: {},
		isDropdownOpen: false,
		posts: { models: {} },
		searchScope: { enabled: false },
		searchQuery: "",
		typeahead: { idsByQuery: {}, models: {} },
		typeaheadByType: { idsByQuery: {}, models: {} },
		viewTreatment: {},
	},
	searchDiscoveryUnits: { headerContent: {}, models: {}, order: {} },
	searchQueryId: {},
	seo: {
		crawler: null,
		linksModule: {
			frontpage: [
				{
					title: "Popular Communities",
					links: [
						{ url: "/r/AskReddit/", visible: true },
						{ url: "/r/NoStupidQuestions/", visible: true },
						{ url: "/r/DestinyTheGame/", visible: true },
						{ url: "/r/explainlikeimfive/", visible: true },
						{ url: "/r/leagueoflegends/", visible: true },
						{ url: "/r/Minecraft/", visible: true },
						{ url: "/r/IAmA/", visible: true },
						{ url: "/r/OutOfTheLoop/", visible: true },
						{ url: "/r/discordapp/", visible: true },
						{ url: "/r/FIFA/", visible: true },
						{ url: "/r/Instagram/", visible: true },
						{ url: "/r/Twitch/", visible: true },
						{ url: "/r/FortNiteBR/", visible: true },
						{ url: "/r/NintendoSwitch/", visible: true },
						{ url: "/r/NBA2k/", visible: true },
						{ url: "/r/gtaonline/", visible: true },
						{ url: "/r/Tinder/", visible: true },
						{ url: "/r/xboxone/", visible: true },
						{ url: "/r/relationship_advice/", visible: true },
						{ url: "/r/Amd/", visible: true },
						{ url: "/r/todayilearned/", visible: true },
						{ url: "/r/sysadmin/", visible: true },
						{ url: "/r/OnePiece/", visible: true },
						{ url: "/r/askscience/", visible: true },
						{ url: "/r/2007scape/", visible: true },
						{ url: "/r/pics/", visible: true },
						{ url: "/r/MonsterHunterWorld/", visible: true },
						{ url: "/r/legaladvice/", visible: true },
						{ url: "/r/Showerthoughts/", visible: true },
						{ url: "/r/pcmasterrace/", visible: true },
						{ url: "/r/LifeProTips/", visible: true },
						{ url: "/r/breakingbad/", visible: true },
						{ url: "/r/singapore/", visible: true },
						{ url: "/r/AskCulinary/", visible: true },
						{ url: "/r/FORTnITE/", visible: true },
						{ url: "/r/netflix/", visible: true },
						{ url: "/r/tipofmytongue/", visible: true },
						{ url: "/r/DotA2/", visible: true },
						{ url: "/r/nvidia/", visible: true },
						{ url: "/r/books/", visible: true },
						{ url: "/r/DunderMifflin/", visible: true },
						{ url: "/r/memes/", visible: true },
						{ url: "/r/baseball/", visible: true },
						{ url: "/r/learnpython/", visible: true },
						{ url: "/r/keto/", visible: true },
						{ url: "/r/Windows10/", visible: true },
						{ url: "/r/Sneakers/", visible: true },
						{ url: "/r/Frugal/", visible: true },
						{ url: "/r/learnprogramming/", visible: true },
						{ url: "/r/Overwatch/", visible: true },
						{ url: "/r/southpark/", visible: true },
						{ url: "/r/piercing/", visible: true },
						{ url: "/r/canada/", visible: true },
						{ url: "/r/skyrim/", visible: true },
						{ url: "/r/worldnews/", visible: true },
						{ url: "/r/nosleep/", visible: true },
					],
				},
				{
					title: "Gaming",
					links: [
						{ url: "/r/StardewValley/", visible: true },
						{ url: "/r/FortniteCompetitive/", visible: true },
						{ url: "/r/totalwar/", visible: true },
						{ url: "/r/Fallout/", visible: true },
						{ url: "/r/RocketLeague/", visible: true },
						{ url: "/r/fo76/", visible: true },
						{ url: "/r/yugioh/", visible: true },
						{ url: "/r/ClashRoyale/", visible: true },
						{ url: "/r/boardgames/", visible: true },
						{ url: "/r/thedivision/", visible: true },
						{ url: "/r/elderscrollsonline/", visible: true },
						{ url: "/r/runescape/", visible: true },
						{ url: "/r/Blackops4/", visible: true },
						{ url: "/r/fireemblem/", visible: true },
						{ url: "/r/CrusaderKings/", visible: true },
						{ url: "/r/Breath_of_the_Wild/", visible: true },
						{ url: "/r/PUBGMobile/", visible: true },
						{ url: "/r/Warhammer40k/", visible: true },
						{ url: "/r/Brawlstars/", visible: true },
						{ url: "/r/summonerswar/", visible: true },
						{ url: "/r/MLBTheShow/", visible: true },
						{ url: "/r/SWGalaxyOfHeroes/", visible: true },
						{ url: "/r/BattlefieldV/", visible: true },
						{ url: "/r/deadbydaylight/", visible: true },
						{ url: "/r/MagicArena/", visible: true },
						{ url: "/r/Smite/", visible: true },
						{ url: "/r/starcitizen/", visible: true },
						{ url: "/r/Persona5/", visible: true },
						{ url: "/r/MortalKombat/", visible: true },
						{ url: "/r/tf2/", visible: true },
						{ url: "/r/playrust/", visible: true },
						{ url: "/r/PSVR/", visible: true },
						{ url: "/r/RimWorld/", visible: true },
						{ url: "/r/ClashOfClans/", visible: true },
						{ url: "/r/FireEmblemHeroes/", visible: true },
						{ url: "/r/Terraria/", visible: true },
						{ url: "/r/osugame/", visible: true },
						{ url: "/r/NoMansSkyTheGame/", visible: true },
						{ url: "/r/forhonor/", visible: true },
						{ url: "/r/EliteDangerous/", visible: true },
						{ url: "/r/Warthunder/", visible: true },
						{ url: "/r/Seaofthieves/", visible: true },
						{ url: "/r/Paladins/", visible: true },
						{ url: "/r/StarWarsBattlefront/", visible: true },
						{ url: "/r/dauntless/", visible: true },
						{ url: "/r/FFBraveExvius/", visible: true },
						{ url: "/r/TwoBestFriendsPlay/", visible: true },
						{ url: "/r/Competitiveoverwatch/", visible: true },
						{ url: "/r/DuelLinks/", visible: true },
						{ url: "/r/Eve/", visible: true },
						{ url: "/r/danganronpa/", visible: true },
						{ url: "/r/halo/", visible: true },
						{ url: "/r/Destiny/", visible: true },
						{ url: "/r/pesmobile/", visible: true },
						{ url: "/r/CoDCompetitive/", visible: true },
						{ url: "/r/future_fight/", visible: true },
						{ url: "/r/DaysGone/", visible: true },
						{ url: "/r/ModernMagic/", visible: true },
						{ url: "/r/girlsfrontline/", visible: true },
						{ url: "/r/fivenightsatfreddys/", visible: true },
						{ url: "/r/NHLHUT/", visible: true },
						{ url: "/r/WorldofTanks/", visible: true },
						{ url: "/r/Gamingcirclejerk/", visible: true },
						{ url: "/r/Mordhau/", visible: true },
						{ url: "/r/battlestations/", visible: true },
						{ url: "/r/FUTMobile/", visible: true },
						{ url: "/r/Market76/", visible: true },
						{ url: "/r/pokemontrades/", visible: true },
					],
				},
				{
					title: "Sports",
					links: [
						{ url: "/r/soccer/", visible: true },
						{ url: "/r/hockey/", visible: true },
						{ url: "/r/CFB/", visible: true },
						{ url: "/r/barstoolsports/", visible: true },
						{ url: "/r/airsoft/", visible: true },
						{ url: "/r/rugbyunion/", visible: true },
						{ url: "/r/golf/", visible: true },
						{ url: "/r/MTB/", visible: true },
						{ url: "/r/cycling/", visible: true },
						{ url: "/r/Boxing/", visible: true },
						{ url: "/r/bicycling/", visible: true },
						{ url: "/r/sportsbook/", visible: true },
						{ url: "/r/hockeyplayers/", visible: true },
						{ url: "/r/NewSkaters/", visible: true },
						{ url: "/r/Astros/", visible: true },
						{ url: "/r/footballmanagergames/", visible: true },
						{ url: "/r/WWEGames/", visible: true },
						{ url: "/r/Nationals/", visible: true },
						{ url: "/r/GreenBayPackers/", visible: true },
						{ url: "/r/Patriots/", visible: true },
						{ url: "/r/sports/", visible: true },
						{ url: "/r/reddevils/", visible: true },
						{ url: "/r/LiverpoolFC/", visible: true },
						{ url: "/r/NYYankees/", visible: true },
						{ url: "/r/tennis/", visible: true },
						{ url: "/r/FantasyPL/", visible: true },
						{ url: "/r/WWE/", visible: true },
						{ url: "/r/Dodgers/", visible: true },
						{ url: "/r/NFA/", visible: true },
						{ url: "/r/eagles/", visible: true },
						{ url: "/r/sixers/", visible: true },
						{ url: "/r/Browns/", visible: true },
						{ url: "/r/detroitlions/", visible: true },
						{ url: "/r/discgolf/", visible: true },
						{ url: "/r/Cricket/", visible: true },
						{ url: "/r/MLS/", visible: true },
						{ url: "/r/canucks/", visible: true },
						{ url: "/r/DynastyFF/", visible: true },
						{ url: "/r/minnesotavikings/", visible: true },
						{ url: "/r/cowboys/", visible: true },
						{ url: "/r/snowboarding/", visible: true },
						{ url: "/r/nrl/", visible: true },
						{ url: "/r/Braves/", visible: true },
						{ url: "/r/Cardinals/", visible: true },
						{ url: "/r/bikecommuting/", visible: true },
						{ url: "/r/CHIBears/", visible: true },
						{ url: "/r/ravens/", visible: true },
						{ url: "/r/coys/", visible: true },
						{ url: "/r/Mavericks/", visible: true },
						{ url: "/r/nyjets/", visible: true },
						{ url: "/r/nbadiscussion/", visible: true },
						{ url: "/r/chelseafc/", visible: true },
						{ url: "/r/bostonceltics/", visible: true },
						{ url: "/r/Fishing/", visible: true },
						{ url: "/r/NYKnicks/", visible: true },
						{ url: "/r/LosAngelesRams/", visible: true },
						{ url: "/r/steelers/", visible: true },
						{ url: "/r/nhl/", visible: true },
						{ url: "/r/FixedGearBicycle/", visible: true },
						{ url: "/r/fantasybaseball/", visible: true },
						{ url: "/r/Barca/", visible: true },
						{ url: "/r/denvernuggets/", visible: true },
						{ url: "/r/realmadrid/", visible: true },
						{ url: "/r/suns/", visible: true },
						{ url: "/r/NBASpurs/", visible: true },
						{ url: "/r/tampabayrays/", visible: true },
						{ url: "/r/peloton/", visible: true },
						{ url: "/r/AtlantaUnited/", visible: true },
						{ url: "/r/minnesotatwins/", visible: true },
						{ url: "/r/SanJoseSharks/", visible: true },
						{ url: "/r/Torontobluejays/", visible: true },
						{ url: "/r/ripcity/", visible: true },
						{ url: "/r/flyfishing/", visible: true },
						{ url: "/r/MCFC/", visible: true },
						{ url: "/r/balisong/", visible: true },
						{ url: "/r/redsox/", visible: true },
						{ url: "/r/LigaMX/", visible: true },
						{ url: "/r/phillies/", visible: true },
						{ url: "/r/NewYorkMets/", visible: true },
						{ url: "/r/SFGiants/", visible: true },
						{ url: "/r/ACMilan/", visible: true },
					],
				},
				{
					title: "TV",
					links: [
						{ url: "/r/rupaulsdragrace/", visible: true },
						{ url: "/r/90DayFiance/", visible: true },
						{ url: "/r/dbz/", visible: true },
						{ url: "/r/Boruto/", visible: true },
						{ url: "/r/rickandmorty/", visible: true },
						{ url: "/r/howardstern/", visible: true },
						{ url: "/r/cordcutters/", visible: true },
						{ url: "/r/TheLastAirbender/", visible: true },
						{ url: "/r/IASIP/", visible: true },
						{ url: "/r/stevenuniverse/", visible: true },
						{ url: "/r/brooklynninenine/", visible: true },
						{ url: "/r/thebachelor/", visible: true },
						{ url: "/r/TheSimpsons/", visible: true },
						{ url: "/r/thewalkingdead/", visible: true },
						{ url: "/r/MtvChallenge/", visible: true },
						{ url: "/r/StrangerThings/", visible: true },
						{ url: "/r/survivor/", visible: true },
						{ url: "/r/thesopranos/", visible: true },
						{ url: "/r/batman/", visible: true },
						{ url: "/r/BravoRealHousewives/", visible: true },
						{ url: "/r/blackmirror/", visible: true },
						{ url: "/r/NetflixBestOf/", visible: true },
						{ url: "/r/Berserk/", visible: true },
						{ url: "/r/BlackClover/", visible: true },
						{ url: "/r/riverdale/", visible: true },
						{ url: "/r/BoJackHorseman/", visible: true },
						{ url: "/r/lucifer/", visible: true },
						{ url: "/r/TheBlackList/", visible: true },
						{ url: "/r/TeenMomOGandTeenMom2/", visible: true },
						{ url: "/r/overlord/", visible: true },
						{ url: "/r/trailerparkboys/", visible: true },
						{ url: "/r/BigBrother/", visible: true },
						{ url: "/r/PandR/", visible: true },
						{ url: "/r/community/", visible: true },
						{ url: "/r/adventuretime/", visible: true },
						{ url: "/r/Konosuba/", visible: true },
						{ url: "/r/fairytail/", visible: true },
						{ url: "/r/touhou/", visible: true },
						{ url: "/r/the100/", visible: true },
						{ url: "/r/scifi/", visible: true },
						{ url: "/r/titanfolk/", visible: true },
						{ url: "/r/TheHandmaidsTale/", visible: true },
						{ url: "/r/criterion/", visible: true },
						{ url: "/r/westworld/", visible: true },
						{ url: "/r/DanLeBatardShow/", visible: true },
						{ url: "/r/mylittlepony/", visible: true },
						{ url: "/r/Jeopardy/", visible: true },
						{ url: "/r/SpoiledDragRace/", visible: true },
						{ url: "/r/Gundam/", visible: true },
						{ url: "/r/MakingaMurderer/", visible: true },
						{ url: "/r/vanderpumprules/", visible: true },
						{ url: "/r/StarVStheForcesofEvil/", visible: true },
						{ url: "/r/anime_irl/", visible: true },
						{ url: "/r/TheDickShow/", visible: true },
						{ url: "/r/rpdrcringe/", visible: true },
						{ url: "/r/TheAmazingRace/", visible: true },
						{ url: "/r/LegendsOfTomorrow/", visible: true },
						{ url: "/r/marvelmemes/", visible: true },
						{ url: "/r/ImaginaryWesteros/", visible: true },
						{ url: "/r/HBOGameofThrones/", visible: true },
						{ url: "/r/GameOfThronesMemes/", visible: true },
						{ url: "/r/aSongOfMemesAndRage/", visible: true },
					],
				},
				{
					title: "Travel",
					links: [
						{ url: "/r/vancouver/", visible: true },
						{ url: "/r/brasil/", visible: true },
						{ url: "/r/australia/", visible: true },
						{ url: "/r/mexico/", visible: true },
						{ url: "/r/argentina/", visible: true },
						{ url: "/r/ottawa/", visible: true },
						{ url: "/r/ireland/", visible: true },
						{ url: "/r/travel/", visible: true },
						{ url: "/r/Calgary/", visible: true },
						{ url: "/r/india/", visible: true },
						{ url: "/r/italy/", visible: true },
						{ url: "/r/AskNYC/", visible: true },
						{ url: "/r/europe/", visible: true },
						{ url: "/r/sydney/", visible: true },
						{ url: "/r/france/", visible: true },
						{ url: "/r/dubai/", visible: true },
						{ url: "/r/Edmonton/", visible: true },
						{ url: "/r/CasualUK/", visible: true },
						{ url: "/r/malaysia/", visible: true },
						{ url: "/r/askTO/", visible: true },
						{ url: "/r/JapanTravel/", visible: true },
						{ url: "/r/solotravel/", visible: true },
						{ url: "/r/newzealand/", visible: true },
						{ url: "/r/Turkey/", visible: true },
						{ url: "/r/Portland/", visible: true },
						{ url: "/r/thenetherlands/", visible: true },
						{ url: "/r/Atlanta/", visible: true },
						{ url: "/r/brisbane/", visible: true },
						{ url: "/r/halifax/", visible: true },
						{ url: "/r/chile/", visible: true },
						{ url: "/r/Winnipeg/", visible: true },
						{ url: "/r/japanlife/", visible: true },
						{ url: "/r/philadelphia/", visible: true },
						{ url: "/r/hungary/", visible: true },
						{ url: "/r/sandiego/", visible: true },
						{ url: "/r/Denver/", visible: true },
						{ url: "/r/Romania/", visible: true },
						{ url: "/r/translator/", visible: true },
						{ url: "/r/Dallas/", visible: true },
						{ url: "/r/Columbus/", visible: true },
						{ url: "/r/pittsburgh/", visible: true },
						{ url: "/r/berkeley/", visible: true },
						{ url: "/r/nashville/", visible: true },
						{ url: "/r/VictoriaBC/", visible: true },
						{ url: "/r/greece/", visible: true },
						{ url: "/r/WaltDisneyWorld/", visible: true },
						{ url: "/r/Austria/", visible: true },
						{ url: "/r/Sacramento/", visible: true },
						{ url: "/r/kansascity/", visible: true },
						{ url: "/r/croatia/", visible: true },
						{ url: "/r/sanfrancisco/", visible: true },
						{ url: "/r/vzla/", visible: true },
						{ url: "/r/Suomi/", visible: true },
						{ url: "/r/Denmark/", visible: true },
						{ url: "/r/orangecounty/", visible: true },
						{ url: "/r/nova/", visible: true },
						{ url: "/r/Minneapolis/", visible: true },
						{ url: "/r/saskatoon/", visible: true },
						{ url: "/r/SaltLakeCity/", visible: true },
						{ url: "/r/NewOrleans/", visible: true },
						{ url: "/r/Polska/", visible: true },
						{ url: "/r/Wellington/", visible: true },
						{ url: "/r/rva/", visible: true },
						{ url: "/r/Adelaide/", visible: true },
						{ url: "/r/brasilivre/", visible: true },
						{ url: "/r/Scotland/", visible: true },
						{ url: "/r/indonesia/", visible: true },
						{ url: "/r/IWantOut/", visible: true },
						{ url: "/r/serbia/", visible: true },
						{ url: "/r/rollercoasters/", visible: true },
						{ url: "/r/Detroit/", visible: true },
						{ url: "/r/sanantonio/", visible: true },
						{ url: "/r/Israel/", visible: true },
						{ url: "/r/Shoestring/", visible: true },
						{ url: "/r/podemos/", visible: true },
						{ url: "/r/newsokur/", visible: true },
						{ url: "/r/vagabond/", visible: true },
						{ url: "/r/TurkeyJerky/", visible: true },
						{ url: "/r/roadtrip/", visible: true },
						{ url: "/r/cirkeltrek/", visible: true },
					],
				},
				{
					title: "Health \u0026 Fitness",
					links: [
						{ url: "/r/orangetheory/", visible: true },
						{ url: "/r/bodybuilding/", visible: true },
						{ url: "/r/bodyweightfitness/", visible: true },
						{ url: "/r/vegan/", visible: true },
						{ url: "/r/crossfit/", visible: true },
						{ url: "/r/nattyorjuice/", visible: true },
						{ url: "/r/loseit/", visible: true },
						{ url: "/r/xxfitness/", visible: true },
						{ url: "/r/powerlifting/", visible: true },
						{ url: "/r/1200isplenty/", visible: true },
						{ url: "/r/GetMotivated/", visible: true },
						{ url: "/r/intermittentfasting/", visible: true },
						{ url: "/r/CampingGear/", visible: true },
						{ url: "/r/skiing/", visible: true },
						{ url: "/r/leangains/", visible: true },
						{ url: "/r/progresspics/", visible: true },
						{ url: "/r/amateur_boxing/", visible: true },
						{ url: "/r/CampingandHiking/", visible: true },
						{ url: "/r/diabetes/", visible: true },
						{ url: "/r/Supplements/", visible: true },
						{ url: "/r/boostedboards/", visible: true },
						{ url: "/r/backpacking/", visible: true },
						{ url: "/r/camping/", visible: true },
						{ url: "/r/Stronglifts5x5/", visible: true },
						{ url: "/r/hiking/", visible: true },
						{ url: "/r/Brogress/", visible: true },
						{ url: "/r/migraine/", visible: true },
						{ url: "/r/C25K/", visible: true },
						{ url: "/r/HealthyFood/", visible: true },
						{ url: "/r/ehlersdanlos/", visible: true },
						{ url: "/r/swoleacceptance/", visible: true },
						{ url: "/r/EOOD/", visible: true },
						{ url: "/r/EDanonymemes/", visible: true },
						{ url: "/r/diabetes_t1/", visible: true },
						{ url: "/r/medical_advice/", visible: true },
					],
				},
				{
					title: "Fashion",
					links: [
						{ url: "/r/MakeupAddiction/", visible: true },
						{ url: "/r/Watches/", visible: true },
						{ url: "/r/BeautyGuruChatter/", visible: true },
						{ url: "/r/frugalmalefashion/", visible: true },
						{ url: "/r/poshmark/", visible: true },
						{ url: "/r/tattoos/", visible: true },
						{ url: "/r/beards/", visible: true },
						{ url: "/r/goodyearwelt/", visible: true },
						{ url: "/r/Repsneakers/", visible: true },
						{ url: "/r/fragrance/", visible: true },
						{ url: "/r/LushCosmetics/", visible: true },
						{ url: "/r/malelivingspace/", visible: true },
						{ url: "/r/BeautyBoxes/", visible: true },
						{ url: "/r/beauty/", visible: true },
						{ url: "/r/Makeup/", visible: true },
						{ url: "/r/wicked_edge/", visible: true },
						{ url: "/r/rawdenim/", visible: true },
						{ url: "/r/RedditLaqueristas/", visible: true },
						{ url: "/r/Hair/", visible: true },
						{ url: "/r/Indiemakeupandmore/", visible: true },
						{ url: "/r/MUAontheCheap/", visible: true },
						{ url: "/r/Watchexchange/", visible: true },
						{ url: "/r/yeezys/", visible: true },
						{ url: "/r/streetwearstartup/", visible: true },
						{ url: "/r/findfashion/", visible: true },
						{ url: "/r/femalehairadvice/", visible: true },
						{ url: "/r/PanPorn/", visible: true },
						{ url: "/r/rolex/", visible: true },
						{ url: "/r/acne/", visible: true },
						{ url: "/r/Wetshaving/", visible: true },
						{ url: "/r/Youniqueamua/", visible: true },
						{ url: "/r/sneakermarket/", visible: true },
						{ url: "/r/SarahSnark/", visible: true },
						{ url: "/r/RepLadiesBST/", visible: true },
						{ url: "/r/makeupexchange/", visible: true },
					],
				},
			],
		},
		topicLinks: {},
	},
	shortcuts: { activeCommentId: null, activePostId: null, namespace: "Listing" },
	sidebarPromotedPosts: { firstFetch: false, models: {} },
	structuredStyles: {
		draft: {},
		exportStyles: { error: null, pending: false },
		flairTemplate: { models: {} },
		imagePreviews: {},
		isBladeEditorDirty: false,
		isEditing: null,
		models: {},
	},
	stylesheets: "https://www.redditstatic.com/desktop2x/chunkCSS/Reddit.401bac5158b118bca775_.css",
	subredditAutocomplete: { api: { error: {}, pending: {} }, models: {} },
	subreddits: {
		about: {},
		api: {
			about: { error: {}, pending: false },
			create: { error: { apiError: null }, lastCreatedSubredditId: null, initialCrosspost: null, pending: false },
			inlineEditing: { pending: false },
			models: { error: {}, pending: {} },
			onboarding: { pending: {} },
			productOffers: { error: null, pending: false },
			rankings: { error: null, pending: false },
			rules: false,
			settings: { pending: false },
			similar: { pending: {} },
			topContent: { error: {}, pending: {} },
			wiki: { error: {}, pending: {} },
		},
		appliedFilters: { meta: {} },
		byCategory: {},
		carousel: { pending: false, items: {} },
		communityInfo: {},
		countrySiteSettings: {},
		crosspostable: { api: { errors: null, pending: false }, ids: {} },
		duplicates: { models: {} },
		gov: { assets: {}, communityRaw: {}, distributions: {}, releaseNotes: {} },
		models: {
			t5_36buk: {
				url: "/r/thebutton/",
				displayText: "r/thebutton",
				icon: { url: "", width: null, height: null },
				type: "archived",
				primaryColor: "",
				whitelistStatus: "no_ads",
				wls: 0,
				freeFormReports: true,
				id: "t5_36buk",
				isQuarantined: false,
				isNSFW: false,
				isSubscribed: false,
				name: "thebutton",
				subscribers: 127076,
				title: "the button",
				allowPredictions: false,
				allowPredictionsTournament: false,
			},
			t5_3d7hf: {
				url: "/r/joinrobin/",
				displayText: "r/joinrobin",
				icon: { url: "", width: null, height: null },
				type: "archived",
				primaryColor: "",
				whitelistStatus: "no_ads",
				wls: 0,
				freeFormReports: true,
				id: "t5_3d7hf",
				isQuarantined: false,
				isNSFW: false,
				isSubscribed: false,
				name: "joinrobin",
				subscribers: 8288,
				title: "Join Robin",
				allowPredictions: false,
				allowPredictionsTournament: false,
			},
			t5_2sxhs: {
				url: "/r/place/",
				displayText: "r/place",
				icon: { url: "https://styles.redditmedia.com/t5_2sxhs/styles/communityIcon_5ejpm2gtctq81.png", width: null, height: null },
				communityIcon: "https://styles.redditmedia.com/t5_2sxhs/styles/communityIcon_5ejpm2gtctq81.png",
				type: "archived",
				primaryColor: "#FF4500",
				whitelistStatus: "house_only",
				wls: 1,
				freeFormReports: true,
				id: "t5_2sxhs",
				isQuarantined: false,
				isNSFW: false,
				isSubscribed: false,
				name: "place",
				subscribers: 7671586,
				title: "place",
				allowPredictions: false,
				allowPredictionsTournament: false,
			},
			t5_gxikd: {
				url: "/r/thanosdidnothingwrong/",
				displayText: "r/thanosdidnothingwrong",
				icon: { url: "https://b.thumbs.redditmedia.com/ZgUpd2ompjMC0a6Mek4j-F_tvv-p-Csfr1aGx_fHY9Y.png", width: 256, height: 256 },
				communityIcon: "https://styles.redditmedia.com/t5_gxikd/styles/communityIcon_uvi1p72gro821.png",
				type: "restricted",
				primaryColor: "#1B2B42",
				whitelistStatus: "all_ads",
				wls: 6,
				freeFormReports: true,
				id: "t5_gxikd",
				isQuarantined: false,
				isNSFW: false,
				isSubscribed: false,
				name: "thanosdidnothingwrong",
				subscribers: 638608,
				title: "ThanosDidNothingWrong",
				allowPredictions: false,
				allowPredictionsTournament: false,
			},
			t5_2rjli: {
				url: "/r/teenagers/",
				displayText: "r/teenagers",
				icon: { url: "https://b.thumbs.redditmedia.com/uUYtnr8UF4a5QThBaOLZBs0s__b1o66d8OZz3fOcxrk.png", width: 256, height: 256 },
				communityIcon: "https://styles.redditmedia.com/t5_2rjli/styles/communityIcon_woz69bbppdzb1.png",
				type: "public",
				primaryColor: "#B8001F",
				whitelistStatus: "no_ads",
				wls: 0,
				freeFormReports: true,
				answerableQuestions: [],
				id: "t5_2rjli",
				isQuarantined: false,
				isNSFW: false,
				isSubscribed: true,
				name: "teenagers",
				subscribers: 3050686,
				title: "r/teenagers",
				allowPredictions: false,
				allowPredictionsTournament: false,
			},
		},
		moderated: { api: { errors: null, fetched: false, pending: false }, order: null },
		notificationSettings: {},
		onboarding: {},
		powerupRecentSupporters: {},
		powerups: {},
		powerupsEmojis: {},
		productOffers: {},
		products: {},
		progressModule: {},
		questions: {},
		rankings: {},
		rankingsPageInfo: {},
		related: {},
		rules: {},
		settings: {},
		similar: {},
		mutedSubreddits: { ids: [], subreddits: [] },
		survey: {},
		topContent: {},
		trending: ["t5_36buk", "t5_3d7hf", "t5_2sxhs", "t5_gxikd"],
		unavailableModels: {},
	},
	subredditStickyPosts: { data: {} },
	subscriptions: {
		api: { errors: null, fetched: false, pending: false },
		favoriteMultiOrder: [],
		favoriteProfileOrder: [],
		favoriteSubredditOrder: [],
		multiredditOrder: [],
		profileOrder: [],
		subredditOrder: [],
	},
	survey: { activeDemoTrigger: null, demoTriggerThreshold: 1, isDemoEnabled: false, isSampleFactorEnabled: true, surveyNameCalledImmediately: "" },
	tabBadged: false,
	tags: {
		api: {
			create: { pending: false, error: false },
			deleteTag: { pending: false, error: false },
			fetch: { pending: false, error: false },
			update: { pending: false, error: false },
			updatePrimaryTag: { pending: false, error: false },
		},
		availableGlobalTagOrder: { global: [], recommendedGlobal: [] },
		models: {
			globalSubredditTags: {},
			subredditScopedTags: {},
			itemTags: {},
			geoPlaces: {},
			suggestedItemTags: {},
			sortedItemTags: {},
			subredditPrimaryTagId: {},
		},
		selected: {
			selectedPrimaryTagId: {},
			selectedOptions: {},
			selectedSuggestedOptions: {},
			deselectedOptions: {},
			deselectedSuggestedOptions: {},
			inputByItemId: {},
			suggestedInputByItemId: {},
		},
		creation: { selectedOptions: [], tagInput: "", selectedPrimaryTagId: null },
	},
	themes: {},
	toaster: [],
	tooltip: { params: null, tooltipId: null },
	tracing: {},
	tracking: { reCaptchaEnterprise: { load: 0, execute: 0, send: 0, reCaptchaEnterpriseToken: "" }, viewportDataLoaded: {} },
	trafficStats: { pending: false, trafficStats: null },
	transfers: { communityPoints: { api: { error: null, pending: false }, contentId: null, initialRecipient: "", publicAddress: null } },
	trending: { models: {} },
	trophies: {},
	uploads: {},
	user: {
		account: {
			karma: { fromAwardsReceived: 0, fromAwardsGiven: 0, fromComments: 45250, fromPosts: 45594, total: 90844 },
			hasUserProfile: true,
			id: "t2_lbvcrez58",
			isGold: true,
			url: "/user/Littux",
			accountIcon: "https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZTY0YmI3ZGQwYTEzYWY2MjJlMGRlNjQ1NmQxYmJhZGM4ZDFlYzA5ZF80MDk2_rare_85a84975-0333-49e7-ba53-f957e144be02-headshot.png",
			displayText: "Littux",
			hasExternalAccount: false,
			snoovatarFullBodyAsset: "https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZTY0YmI3ZGQwYTEzYWY2MjJlMGRlNjQ1NmQxYmJhZGM4ZDFlYzA5ZF80MDk2_rare_85a84975-0333-49e7-ba53-f957e144be02.png",
			profileId: "t5_9jsumn",
			canCreateSubreddit: true,
			coins: 69,
			created: 1645968649,
			goldExpiration: 1722545776,
			hasUnreadMail: true,
			hasUnreadModmail: true,
			hasUnreadOldModmail: true,
			hasVerifiedEmail: true,
			inboxCount: 1630,
			inRedesignBeta: true,
			isEmployee: true,
			isFPR: false,
			isNameEditable: false,
			isMod: true,
			isPasswordSet: true,
			isSuspended: false,
			suspensionExpirationUtc: null,
			nightmode: true,
			seenLayoutSwitch: true,
			seenRedesignModal: false,
			seenSubredditChatFtux: false,
			showRecentPosts: true,
			showTrending: true,
			hasGoldSubscription: true,
			hasPaypalSubscription: false,
			hasStripeSubscription: true,
		},
		accountSettings: { changeEmail: { api: { error: null, pending: false } }, sendResetEmail: { api: { pending: false, emailSent: false } } },
		blocked: {
			api: {},
			data: [
				{
					date: 1662796688,
					rel_id: "r9_449j81",
					icon_img:
						"https://styles.redditmedia.com/t5_6adbx7/styles/profileIcon_yf99w0ipxjy81.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=02ad3cb6a2e48e24347949eff7a9b419ab1b92c6",
					name: "readingeggs_official",
					id: "t2_mflno2ui",
				},
				{
					date: 1663482168,
					rel_id: "r9_45ayjz",
					icon_img:
						"https://styles.redditmedia.com/t5_5wgj85/styles/profileIcon_9xhtjmxxcen91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=928bf8b57f0c778d001c430162bc62816603270e",
					name: "LightningLinkCasino",
					id: "t2_jzx2pqms",
				},
				{
					date: 1663576997,
					rel_id: "r9_45g87j",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_2.png",
					name: "jorodde",
					id: "t2_oqh5irqq",
				},
				{
					date: 1663724575,
					rel_id: "r9_45p5b5",
					icon_img:
						"https://styles.redditmedia.com/t5_50sb3m/styles/profileIcon_by1t11rofqs71.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=442132bf287f646ac81104b79e7df1f25a0a61d2",
					name: "Bluebet",
					id: "t2_eg0gzkql",
				},
				{
					date: 1663752406,
					rel_id: "r9_45qj24",
					icon_img:
						"https://styles.redditmedia.com/t5_6lnwkr/styles/profileIcon_46jwsg239yj91.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=b2273524c7548c2821e1671349658897226109e5",
					name: "FiveStarGamesAU",
					id: "t2_p8w19c23",
				},
				{
					date: 1665417330,
					rel_id: "r9_48965k",
					icon_img:
						"https://styles.redditmedia.com/t5_6ezurf/styles/profileIcon_5skfe9wrcb191.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=aa75b74bd5ba4aea3b9605267fc7e9cf2644bd44",
					name: "SydneyFootballClub",
					id: "t2_gv3uj61d",
				},
				{
					date: 1665505053,
					rel_id: "r9_48ksk6",
					icon_img:
						"https://styles.redditmedia.com/t5_5gphys/styles/profileIcon_zhwn1e53436c1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=8e67e1d85f56ccd6787b77336848c11839fd2dfb",
					name: "Vistaprint",
					id: "t2_he8iaecu",
				},
				{
					date: 1666102472,
					rel_id: "r9_49mo7b",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_6.png",
					name: "news_com_au_AUD",
					id: "t2_smep16zy",
				},
				{
					date: 1666401181,
					rel_id: "r9_4a4ilt",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_5.png",
					name: "SpotlightAustralia",
					id: "t2_t436q5st",
				},
				{
					date: 1668397118,
					rel_id: "r9_4dfm2r",
					icon_img:
						"https://styles.redditmedia.com/t5_5wgj85/styles/profileIcon_9xhtjmxxcen91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=928bf8b57f0c778d001c430162bc62816603270e",
					name: "LightningLinkCasino",
					id: "t2_jzx2pqms",
				},
				{
					date: 1668690812,
					rel_id: "r9_4dwdr2",
					icon_img:
						"https://styles.redditmedia.com/t5_17f1tk/styles/profileIcon_lhrw5kt91en51.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=bc03eff7249551e5f272f9f31655c6f76505f760",
					name: "dndbeyond",
					id: "t2_1603lh",
				},
				{
					date: 1669766257,
					rel_id: "r9_4fq4pd",
					icon_img:
						"https://styles.redditmedia.com/t5_65yu00/styles/profileIcon_k3c635f8tmr81.jpeg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=ca45284ccbef2d2a223b88cd857d7f43382a442e",
					name: "FlashNewsAU",
					id: "t2_lk79q0vs",
				},
				{
					date: 1670522051,
					rel_id: "r9_4gym9o",
					icon_img:
						"https://styles.redditmedia.com/t5_4eugqd/styles/profileIcon_f4g6tcv5h4tc1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=703c602286cad8dfc0c18c31af32bf84fb481266",
					name: "_futuresuper",
					id: "t2_5k2s1p3",
				},
				{
					date: 1670522061,
					rel_id: "r9_4gymaf",
					icon_img:
						"https://styles.redditmedia.com/t5_6m4285/styles/profileIcon_vnydwqd3rua91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=7a32c05338ffc47fd9f1870f60654a913a50bf66",
					name: "Capify",
					id: "t2_dud57f48",
				},
				{
					date: 1670524365,
					rel_id: "r9_4gyroj",
					icon_img:
						"https://styles.redditmedia.com/t5_4eugqd/styles/profileIcon_f4g6tcv5h4tc1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=703c602286cad8dfc0c18c31af32bf84fb481266",
					name: "_futuresuper",
					id: "t2_5k2s1p3",
				},
				{
					date: 1671845873,
					rel_id: "r9_4j221j",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_5.png",
					name: "JackboxGames",
					id: "t2_tgadb9v1",
				},
				{
					date: 1671889411,
					rel_id: "r9_4j40bd",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_7.png",
					name: "CHFWater",
					id: "t2_ikhzovrr",
				},
				{
					date: 1673956399,
					rel_id: "r9_4mi23r",
					icon_img:
						"https://styles.redditmedia.com/t5_62ij4i/styles/profileIcon_1twxwibgfiec1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=3f5e070e968e977a1fbf97b48ee080d6d71445ce",
					name: "DabbleSports",
					id: "t2_gczvt0f8",
				},
				{
					date: 1675258411,
					rel_id: "r9_4okn3s",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1675258421,
					rel_id: "r9_4okn4n",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1675258428,
					rel_id: "r9_4okn53",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1675258432,
					rel_id: "r9_4okn5e",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1675258435,
					rel_id: "r9_4okn5l",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1675258438,
					rel_id: "r9_4okn5s",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1675258444,
					rel_id: "r9_4okn6i",
					icon_img:
						"https://styles.redditmedia.com/t5_3jofgf/styles/profileIcon_8yx1flw1ah0c1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=51217603092032f16b549e689328bc6e4492258f",
					name: "obanos68419",
					id: "t2_9a4vdndz",
				},
				{
					date: 1676091535,
					rel_id: "r9_4pxoi2",
					icon_img:
						"https://styles.redditmedia.com/t5_7pc1ks/styles/profileIcon_50bby6e563hc1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=8558e38f52b3d08eb4e057a872d2b44776f15dff",
					name: "iteraio",
					id: "t2_vdqj4og2",
				},
				{
					date: 1676277268,
					rel_id: "r9_4q8v1b",
					icon_img:
						"https://styles.redditmedia.com/t5_4qwdt6/styles/profileIcon_5f2kio5abk1b1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=003a05fc48cefa07b27c2b006ecb4b8ebdfd4542",
					name: "BetterStackHQ",
					id: "t2_bywzx23t",
				},
				{
					date: 1676436497,
					rel_id: "r9_4qje0d",
					icon_img:
						"https://styles.redditmedia.com/t5_2ic5h2/styles/profileIcon_snood110404d-1a6c-4a45-bb71-d2d737416973-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=4e0ab7ab25380f910c558d12e45c2c89b3d2e8b2",
					name: "Destiny2_Official",
					id: "t2_5zl1tjgj",
				},
				{
					date: 1676816830,
					rel_id: "r9_4r6m1a",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_2.png",
					name: "Whatsup136",
					id: "t2_bf5xiv0y",
				},
				{
					date: 1677761620,
					rel_id: "r9_4sudz1",
					icon_img:
						"https://styles.redditmedia.com/t5_72ibyb/styles/profileIcon_gz7fukov76t91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=02e89c727a4dc17d07d35d14cafd1af0021b707b",
					name: "Royal_Match_official",
					id: "t2_sntgxjyu",
				},
				{
					date: 1677986620,
					rel_id: "r9_4t84sc",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_4.png",
					name: "John09643",
					id: "t2_w2z9wv8s",
				},
				{
					date: 1678634649,
					rel_id: "r9_4uco3t",
					icon_img:
						"https://styles.redditmedia.com/t5_7tcws7/styles/profileIcon_afy5iqjfvela1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=1359dc8730a75bbe9f14b4dc58ebd938fb313907",
					name: "myjuniper",
					id: "t2_fz8ihy7m",
				},
				{
					date: 1679041537,
					rel_id: "r9_4v3101",
					icon_img:
						"https://styles.redditmedia.com/t5_72ibyb/styles/profileIcon_gz7fukov76t91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=02e89c727a4dc17d07d35d14cafd1af0021b707b",
					name: "Royal_Match_official",
					id: "t2_sntgxjyu",
				},
				{
					date: 1679049916,
					rel_id: "r9_4v3jwv",
					icon_img:
						"https://styles.redditmedia.com/t5_72ibyb/styles/profileIcon_gz7fukov76t91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=02e89c727a4dc17d07d35d14cafd1af0021b707b",
					name: "Royal_Match_official",
					id: "t2_sntgxjyu",
				},
				{
					date: 1679332047,
					rel_id: "r9_4vpmtq",
					icon_img:
						"https://styles.redditmedia.com/t5_13x7do/styles/profileIcon_tm219avt38wb1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=9e50c6a1d8c0a4fd1ead4b5bb4407fbfe5a6ede5",
					name: "apple",
					id: "t2_2q9crlrw",
				},
				{
					date: 1679333146,
					rel_id: "r9_4vpqde",
					icon_img:
						"https://styles.redditmedia.com/t5_13x7do/styles/profileIcon_tm219avt38wb1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=9e50c6a1d8c0a4fd1ead4b5bb4407fbfe5a6ede5",
					name: "apple",
					id: "t2_2q9crlrw",
				},
				{
					date: 1679435794,
					rel_id: "r9_4vx5sd",
					icon_img:
						"https://styles.redditmedia.com/t5_13x7do/styles/profileIcon_tm219avt38wb1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=9e50c6a1d8c0a4fd1ead4b5bb4407fbfe5a6ede5",
					name: "apple",
					id: "t2_2q9crlrw",
				},
				{
					date: 1679468930,
					rel_id: "r9_4vzcwe",
					icon_img:
						"https://styles.redditmedia.com/t5_62ij4i/styles/profileIcon_1twxwibgfiec1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=3f5e070e968e977a1fbf97b48ee080d6d71445ce",
					name: "DabbleSports",
					id: "t2_gczvt0f8",
				},
				{
					date: 1679924558,
					rel_id: "r9_4wsfm2",
					icon_img:
						"https://styles.redditmedia.com/t5_7i09l/styles/profileIcon_kkyhdg5hpuha1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=791c8cfffb9a28cedd89073ad6f5d095602a2b18",
					name: "palmerbet",
					id: "t2_thgzq",
				},
				{
					date: 1679925317,
					rel_id: "r9_4wshow",
					icon_img:
						"https://styles.redditmedia.com/t5_62ij4i/styles/profileIcon_1twxwibgfiec1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=3f5e070e968e977a1fbf97b48ee080d6d71445ce",
					name: "DabbleSports",
					id: "t2_gczvt0f8",
				},
				{
					date: 1681366211,
					rel_id: "r9_4z2y4z",
					icon_img:
						"https://styles.redditmedia.com/t5_84xxxz/styles/profileIcon_op23faf0dsqa1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=2531897a29f67bdb6a731d1123a214e9701612e3",
					name: "helpfuldownloads",
					id: "t2_bjocn409",
				},
				{
					date: 1682792692,
					rel_id: "r9_51337a",
					icon_img:
						"https://styles.redditmedia.com/t5_7etbyd/styles/profileIcon_snoo27af8726-1141-4960-9a3c-a957d065e954-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=8799c5b0f53c87e90b3a76153aed76edef1e1abe",
					name: "aimassistanalysis",
					id: "t2_udmc86vw",
				},
				{
					date: 1684935144,
					rel_id: "r9_542b96",
					icon_img:
						"https://styles.redditmedia.com/t5_8g55in/styles/profileIcon_snoob5b89f9d-e2d3-41f7-91a6-9571c036711d-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=99cd7292bd61d5c21bb063f820b03147e70d23a3",
					name: "leightonwilson17",
					id: "t2_bt6jsvccq",
				},
				{
					date: 1685873006,
					rel_id: "r9_55oo7d",
					icon_img:
						"https://styles.redditmedia.com/t5_106ffe/styles/profileIcon_snoo7df5702a-812b-4c8f-b74b-f6cfeb288d7e-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=d8fc54967a06f22a7f5d203d0af48cef8350ba0c",
					name: "Major_Liability",
					id: "t2_3movk64d",
				},
				{
					date: 1690635738,
					rel_id: "r9_5dbhj1",
					icon_img:
						"https://styles.redditmedia.com/t5_80p13m/styles/profileIcon_45so3qku68ma1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=7b56632368803f7997cce709c6ced4eaeec2687a",
					name: "FOXTEL",
					id: "t2_w3psiqj9",
				},
				{
					date: 1691327694,
					rel_id: "r9_5e8sm4",
					icon_img:
						"https://styles.redditmedia.com/t5_7s2tbs/styles/profileIcon_snoo9f700059-34d3-4d41-b959-d3985e81e1e6-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=0f641ab88993e8d5b701d284f249e571d4f16d48",
					name: "ChrisRobinsonk",
					id: "t2_vjjvyfiy",
				},
				{
					date: 1691328875,
					rel_id: "r9_5e8urr",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_1.png",
					name: "VapidBondage",
					id: "t2_apm3v4401",
				},
				{
					date: 1692622042,
					rel_id: "r9_5g0iyn",
					icon_img:
						"https://styles.redditmedia.com/t5_94y41y/styles/profileIcon_snoo-nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8xMTUxMzUyOQ_rare_9343cfbf-9661-495b-a391-5eaf19a6845d-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=e20d813f0281acc4775902c2927bd71f8904ffa3",
					name: "Maleficent-Life4990",
					id: "t2_hx4prwrvw",
				},
				{
					date: 1702830337,
					rel_id: "r9_5uc1aq",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_1.png",
					name: "NeanderthalTimes",
					id: "t2_di31yvhl",
				},
				{
					date: 1703658290,
					rel_id: "r9_5vi330",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_6.png",
					name: "brooksrunningau",
					id: "t2_3lwcd7vq",
				},
				{
					date: 1703658303,
					rel_id: "r9_5vi33x",
					icon_img:
						"https://styles.redditmedia.com/t5_vqhtn/styles/profileIcon_zhfo50qzbsn51.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=523a25ff31284ee398fee060802a0aeda6a476b3",
					name: "Atlassian_Official",
					id: "t2_34h6vrmf",
				},
				{
					date: 1703658311,
					rel_id: "r9_5vi34e",
					icon_img:
						"https://styles.redditmedia.com/t5_776ie4/styles/profileIcon_zu8u44zp29zc1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=9c1550aa60ac32786568d0b1cff07e469bb8b302",
					name: "TTCCH",
					id: "t2_tcj4cnjh",
				},
				{
					date: 1703658324,
					rel_id: "r9_5vi356",
					icon_img:
						"https://styles.redditmedia.com/t5_7i88a/styles/profileIcon_d7735kreu2921.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=1ac61318cb2c735c3dc2520212cb95c05ada9e5b",
					name: "HachetteAUS",
					id: "t2_x4ydz9",
				},
				{
					date: 1703658331,
					rel_id: "r9_5vi35m",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_4.png",
					name: "actuni",
					id: "t2_69b676s4",
				},
				{
					date: 1704124933,
					rel_id: "r9_5w74t8",
					icon_img:
						"https://styles.redditmedia.com/t5_6qf0gx/styles/profileIcon_iabaatico0t91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=4b5fb2f0a4d36a6661cd1d086a9bfd6d7ac30062",
					name: "JoinReframe",
					id: "t2_q8pj2o6b",
				},
				{
					date: 1704429782,
					rel_id: "r9_5wot80",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_0.png",
					name: "Due-Star5795",
					id: "t2_bwjia4ts",
				},
				{
					date: 1704514224,
					rel_id: "r9_5wtctr",
					icon_img:
						"https://styles.redditmedia.com/t5_79zst/styles/profileIcon_sq9mmizheai91.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=5ec44713434c4423bf5b8cb19608bf6ef74057ba",
					name: "TT_ads",
					id: "t2_cp97pq4",
				},
				{
					date: 1704588795,
					rel_id: "r9_5wx938",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_0.png",
					name: "Sneasel1",
					id: "t2_krtc11icg",
				},
				{
					date: 1704721876,
					rel_id: "r9_5x4d93",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_6.png",
					name: "jogiadiamonds",
					id: "t2_uyzsdbpq",
				},
				{
					date: 1704767826,
					rel_id: "r9_5x79bh",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8xNzY4MzAwNw_rare_089aa268-3aa6-4b39-b579-2a69cc2dfb11-headshot.png",
					name: "luvvcumm",
					id: "t2_rer8tl4q9",
				},
				{
					date: 1705235444,
					rel_id: "r9_5xvnhx",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8xNzI4NTQ4Mw_rare_f5ce4645-defd-40ea-9993-5a288be3a195-headshot.png",
					name: "imaamalle",
					id: "t2_poa1hqiay",
				},
				{
					date: 1705345778,
					rel_id: "r9_5y1s8g",
					icon_img:
						"https://styles.redditmedia.com/t5_ajekz8/styles/profileIcon_rp0ok066ggcc1.jpg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=1ca10e0a04793bb1770b345d42aba03612a5d47d",
					name: "iCanQuit-NSWGov",
					id: "t2_roawzlc8g",
				},
				{
					date: 1706391347,
					rel_id: "r9_5zkdm1",
					icon_img:
						"https://styles.redditmedia.com/t5_9m5yv0/styles/profileIcon_mwcjn4ko22wb1.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=4b545a8ecf87ec0947110b004e546e698c023d2b",
					name: "DominosAustralia",
					id: "t2_fd15g3vw0",
				},
				{
					date: 1709243610,
					rel_id: "r9_63t8mc",
					icon_img:
						"https://styles.redditmedia.com/t5_3p6prm/styles/profileIcon_snoof7cd39b3-738c-4309-8994-30d595b58d25-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=9f77a46d6b8aebdd4751549a4a10e502db1425e9",
					name: "PsychologicalGas4167",
					id: "t2_9qsq2xyy",
				},
				{
					date: 1709243695,
					rel_id: "r9_63t8un",
					icon_img:
						"https://styles.redditmedia.com/t5_4p3x7e/styles/profileIcon_snoo81de8442-017c-4a3e-b0a7-adedf00559ee-headshot-f.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=2d44d6f48a0c0224eb8d5e50e2f3ddc33f803bf4",
					name: "DonCorleonne44",
					id: "t2_d1zpg8if",
				},
				{
					date: 1709332413,
					rel_id: "r9_63xvw1",
					icon_img:
						"https://styles.redditmedia.com/t5_7w24mh/styles/profileIcon_snoof81adacf-9dd3-4d72-93c4-638ac45f9feb-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=f31b8d922c02c271bcff70376a9262d2612d0a76",
					name: "renpierce96",
					id: "t2_vug7j6e1",
				},
				{
					date: 1709332743,
					rel_id: "r9_63xwna",
					icon_img:
						"https://styles.redditmedia.com/t5_8ummcu/styles/profileIcon_snoo-nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8xMDMxNDk0OA_rare_858b722b-c72f-4edd-99cf-cee090b2b86f-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=f756596f980cfba009333c5341f58a1b5b87b459",
					name: "106170",
					id: "t2_vlsiradv",
				},
				{
					date: 1709379607,
					rel_id: "r9_6406sp",
					icon_img:
						"https://styles.redditmedia.com/t5_12v035/styles/profileIcon_snoo-nftv2_bmZ0X2VpcDE1NToxMzdfNDE2OWZmNGQzMTUwMmNiMWQwOWI4NTA0YTAwYThhNjMyZmIwODQ4Zl8xMzU5MA_rare_5d771899-87db-428f-875c-b873e7cc6bd3-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=e2600ac7d6e8d43b47afae29f7f791a7d1bdc5a6",
					name: "Gabewillo",
					id: "t2_3x7jjday",
				},
				{
					date: 1710327299,
					rel_id: "r9_65e2ll",
					icon_img:
						"https://styles.redditmedia.com/t5_2u9hun/styles/profileIcon_st9orhxuic7d1.jpeg?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=13c0bdda1ed61831b209a073d1edde79a1262696",
					name: "chara_DRumerr",
					id: "t2_6wni3yej",
				},
				{
					date: 1711097524,
					rel_id: "r9_66iqe0",
					icon_img:
						"https://styles.redditmedia.com/t5_3cye1t/styles/profileIcon_snoo7eeefedf-1969-4619-a3b9-7299ecbb5eb8-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=e253f776240796f395b6171967a893fa8e32fb36",
					name: "SnooRobots8645",
					id: "t2_8rjv80b7",
				},
				{
					date: 1712152937,
					rel_id: "r9_683viv",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_1.png",
					name: "Alternative-Hawk-234",
					id: "t2_akdhgv2x",
				},
				{
					date: 1712153564,
					rel_id: "r9_683wta",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8yMTYxMjY1Mw_rare_2f1be07d-6691-4d6a-82f5-99221af8ee1e-headshot.png",
					name: "Outrageous-Load-6294",
					id: "t2_qj0i7zbk0",
				},
				{
					date: 1712160558,
					rel_id: "r9_684c7s",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8xMTA5ODY4OQ_rare_7e57399c-5012-4978-aaba-22c259ae333b-headshot.png",
					name: "Starlight1_99",
					id: "t2_gwf8j1t0h",
				},
				{
					date: 1712160583,
					rel_id: "r9_684cag",
					icon_img:
						"https://styles.redditmedia.com/t5_96vv0/styles/profileIcon_snoo9d0dd192-02a7-4d34-81f2-0a92aaf75e2a-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=f321789949594f22e6af81af181cf36b944faf47",
					name: "j7t21s",
					id: "t2_17acui",
				},
				{
					date: 1712162923,
					rel_id: "r9_684hh4",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8yNTA5NzUwMA_rare_c750ca72-2ac2-4502-bd23-3a6223b74d6a-headshot.png",
					name: "Straight_Farm6024",
					id: "t2_pvkpk4obv",
				},
				{
					date: 1712163399,
					rel_id: "r9_684ind",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8yOTkyODU0MQ_rare_86f6b248-bbf5-40a2-b764-ed74fc9a0d3c-headshot.png",
					name: "FeePurple9114",
					id: "t2_wzd93rn0s",
				},
				{
					date: 1712241352,
					rel_id: "r9_688rfn",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_2.png",
					name: "Dependent_Title_9325",
					id: "t2_xko40y3wq",
				},
				{
					date: 1712241613,
					rel_id: "r9_688rxv",
					icon_img:
						"https://styles.redditmedia.com/t5_6u7w04/styles/profileIcon_snoodc76afa8-bf7c-4fb6-91d4-3f645378d279-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=01c61fcd421dac9b3146f965f7f5323d1001e3a1",
					name: "LandscapeDry3197",
					id: "t2_r08ktnue",
				},
				{
					date: 1712241633,
					rel_id: "r9_688rz8",
					icon_img:
						"https://styles.redditmedia.com/t5_3rkwdo/styles/profileIcon_snoo-nftv2_bmZ0X2VpcDE1NToxMzdfZjMzYWQ4NmJiNTRhMjc4YTZjOWY5YzA3NmY0ZWQ1YTM0YzUzMTk2N18yNTc1MzU_rare_b3332699-31ee-45d5-b6b3-2c721f4617cc-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=491b1e18fb628f1692e1b6a55540c2dfbe9965ae",
					name: "nglFakebot",
					id: "t2_9xxuh71v",
				},
				{
					date: 1712241834,
					rel_id: "r9_688sfa",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_2.png",
					name: "AdImpressive481",
					id: "t2_u5lazrebu",
				},
				{
					date: 1712251598,
					rel_id: "r9_689dl3",
					icon_img: "https://i.redd.it/snoovatar/avatars/d9113b39-d1c2-4454-9289-f904524b2786-headshot.png",
					name: "Icy_Situation_9502",
					id: "t2_qexay1t6",
				},
				{
					date: 1712292914,
					rel_id: "r9_68bwyy",
					icon_img:
						"https://styles.redditmedia.com/t5_6ga7py/styles/profileIcon_snooded00a2a-c581-476f-b360-fbac044dc8da-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=550eeebc8acf0761a82bbc6ea302e5fcdd2d5d6e",
					name: "Wanttd",
					id: "t2_numd0xux",
				},
				{
					date: 1712374614,
					rel_id: "r9_68g8c8",
					icon_img:
						"https://i.redd.it/snoovatar/avatars/nftv2_bmZ0X2VpcDE1NToxMzdfZWI5NTlhNzE1ZGZmZmU2ZjgyZjQ2MDU1MzM5ODJjNDg1OWNiMTRmZV8yMTk4NDA1MQ_rare_795c9214-716f-4923-b3b5-25252aa187a9-headshot.png",
					name: "Aggressive_Tree_3119",
					id: "t2_th3c87yve",
				},
				{
					date: 1712432092,
					rel_id: "r9_68j4fj",
					icon_img:
						"https://styles.redditmedia.com/t5_a1be73/styles/profileIcon_snoo0a264e17-ddb9-4b74-b023-cd587f2bfd91-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=450c2940144ee9f2a75ff5e286330b3548db4a59",
					name: "TooKinkyToDie",
					id: "t2_kt42o4zey",
				},
				{
					date: 1712443766,
					rel_id: "r9_68jtpw",
					icon_img: "https://i.redd.it/snoovatar/avatars/239e34d9-297b-4978-8ab7-38287574e83a-headshot.png",
					name: "First-Following69",
					id: "t2_xndefllqo",
				},
				{
					date: 1713391446,
					rel_id: "r9_69zahf",
					icon_img:
						"https://styles.redditmedia.com/t5_5u1djj/styles/profileIcon_snoo640cc71d-749e-4bc1-adca-c3c28c0a6ff3-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=d78b8ae9c614feba269db9bc52a020cc9321d713",
					name: "UsedImplement6954",
					id: "t2_jkusn6wr",
				},
				{
					date: 1716638162,
					rel_id: "r9_6erwz0",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_0.png",
					name: "WarrenHammer",
					id: "t2_7itkcllc",
				},
				{
					date: 1716764304,
					rel_id: "r9_6ey9yw",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_2.png",
					name: "Important-Tip6610",
					id: "t2_lpjgsctgq",
				},
				{
					date: 1719051388,
					rel_id: "r9_6i6so9",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_3.png",
					name: "hardcock4you316",
					id: "t2_76kj4upf",
				},
				{
					date: 1720176291,
					rel_id: "r9_6jm3hz",
					icon_img:
						"https://styles.redditmedia.com/t5_81g6r4/styles/profileIcon_snooc4220d05-c6f0-4e41-b151-83d771e47085-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=d5a6946318f5d0f82d21ae7e9fb2d0fc9994471d",
					name: "xxthrowxxawayxx4",
					id: "t2_65xon9agh",
				},
				{
					date: 1720228821,
					rel_id: "r9_6joskk",
					icon_img:
						"https://styles.redditmedia.com/t5_3bx1jw/styles/profileIcon_snoofaf89054-9992-4824-af05-b58f58bfb9e1-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=f8bbec8eb9c2285937728e75487be311bed7a397",
					name: "guardshack_",
					id: "t2_775ddi67",
				},
			],
		},
		chatSettings: { invitePolicy: "Everyone" },
		drafts: null,
		experiments: {
			byName: experiments,
			localPersisted: {},
		},
		isCustomizeFlyoutShowing: false,
		topContentDismissalPrefsSet: {},
		language: "en",
		loid: {
			blob: "Z0FBQUFBQm1EcmlSMWg0OV92a0M5WmVTWXpQUERaZERQV3lIYTh6djV0U1BEWUVIckc1S3JaOGJ0bnJ2eTY1QjloODVGR0dHZHZzOS1GRVYwSWJyOGZ4N2NDMHAtWmlYdlZkcXVCRG9CZnJTTzlSMmdjVzdhc3RMdXpEcy05NVdTNlUyTTg1VkNWaWI",
			loid: "0000000000k4vwrnsy",
			loidCreated: "1645962995000",
			version: 2,
		},
		notificationPrefs: {
			api: { getPreferences: { error: null, loaded: false, pending: false }, setPreferences: { error: null, loaded: false, pending: false } },
			subscribedSubredditsSettings: { subreddits: [], pageInfo: null },
			emailSettingsLayout: { sections: { byId: {}, allIds: [] }, rows: { byId: {}, allIds: [] } },
			isAskNotificationPromptVisible: false,
			isNotificationPromptVisible: false,
			preferences: {
				broadcastFollower: false,
				broadcastRecommendation: false,
				chatMessages: false,
				chatRequests: false,
				commentReplies: false,
				communityRecommendations: false,
				liveEvent: false,
				newPinnedPost: false,
				postFlairAdded: false,
				postReplies: false,
				privateMessages: false,
				threadReplies: false,
				topLevelComment: false,
				trendingPosts: false,
				upvotedComments: false,
				upvotedPosts: false,
				userFlairAdded: false,
				usernameMentions: false,
				userNewFollowers: false,
			},
			pushSettingsLayout: { sections: { byId: {}, allIds: [] }, rows: { byId: {}, allIds: [] } },
		},
		ownedBadges: {},
		powerups: { data: null, fetched: false },
		prefs: {
			acceptPrivateMessages: "everyone",
			activityRelevantAds: false,
			allowClickTracking: false,
			autoplayVideo: false,
			collapsedTraySections: { favorites: false, multis: true, moderating: true, subscriptions: false, profiles: false },
			commentMode: "markdown",
			countryCode: "XZ",
			badCommentAutocollapse: "OFF",
			layout: "card",
			rememberCommunityLayout: true,
			defaultCommentSort: "top",
			editorMode: "markdown",
			enableFollowers: true,
			geopopular: "",
			globalTheme: "REDDIT",
			hasSeenCustomizeFlyout: true,
			hideNSFW: false,
			ignoreSuggestedSort: false,
			labelNSFW: true,
			liveBarRecommendationsEnabled: false,
			loginOtpEnabled: false,
			markMessagesRead: false,
			nightmode: false,
			openPostInNewTab: false,
			over18: true,
			reduceAnimationsFromAwards: false,
			searchOver18: true,
			showActiveCommunities: true,
			showPresence: true,
			showTwitter: false,
			sort: "hot",
			stylesEnabled: true,
			subreddit: {},
			subscriptionsPinned: false,
			thirdPartyDataPersonalizedAds: false,
			thirdPartyPersonalizedAds: false,
			thirdPartySiteDataPersonalizedAds: false,
			thirdPartySiteDataPersonalizedContent: false,
			isFirstPartyAdPersonalizationPreferenceShown: true,
			isAdPersonalizationAllowed: true,
			isThirdPartyAdPersonalizationAllowed: true,
			isThirdPartySiteAdPersonalizationAllowed: true,
			isThirdPartyInfoAdPersonalizationAllowed: true,
			topContentDismissalTime: null,
			topContentTimesDismissed: 0,
			rememberCommunitySort: true,
			useMarkdown: true,
			gatedSubredditOptIn: false,
			quarantineOptIn: false,
			sensitiveAdsPreferences: {
				isAlcoholAllowed: true,
				isDatingAllowed: true,
				isGamblingAllowed: true,
				isPregnancyAndParentingAllowed: true,
				isWeightLossAllowed: true,
			},
			collapseReadMessages: false,
			emailDigests: false,
			emailUnreadMessages: false,
			emailUnsubscribe: true,
			hideAds: true,
			hideFromRobots: false,
			highlightComments: true,
			sendWelcomeMessages: true,
			showMessagesInInbox: true,
			showNotifications: true,
			showUsernameMentionNotifications: true,
		},
		productOfferSubscriptions: { status: "default", subscriptions: [] },
		session: {
			accessToken:
				"eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzIwODcyODg5LjE1MDg4NywiaWF0IjoxNzIwNzg2NDg5LjE1MDg4NywianRpIjoiXy1PNkIwamtEVjdNTDNOaUpEWHVKTkxTOTFGeDRnIiwiY2lkIjoiOXRMb0Ywc29wNVJKZ0EiLCJsaWQiOiJ0Ml9rNHZ3cm5zeSIsImFpZCI6InQyX2s0dndybnN5IiwibGNhIjoxNjQ1OTYyOTk1MDAwLCJzY3AiOiJlSnhra2RHT3REQUloZC1sMXo3Ql95cF9OaHRzY1lhc0xRYW9rM243RFZvY2s3MDdjTDRpSFA4bktJcUZMRTJ1QktHa0tXRUZXdE9VTmlMdjU4eTlPWkVGU3lGVFI4NDN5d29rYVVwUFVtTjVweWxSd1daa0xsZmFzVUtEQjZZcFZTNloyMEtQUzV2UTNJMUZ6MDZNcWx4V0h0VFlvM0pwYkdNSzJ4UGp6Y1pxUXlxdXk2bE1ZRmtvbjhXTGZ2eUctdFktZjdiZmhIWXdyS2dLRF9UT3VGeHdZX0hERkhiX25wcjBiRjJ3cUwzWGc5US0xLU4yN2JObW9kbTVfVnpQdnphU2NUbUc1aWZZdjd0LUNSMTQ1SG1aVVFjd1lnMF95ckFqNl9Ddk9vREtCUVdNSlloUEk1QXJsMl9fSmRpdVRmOGF0eWQtLUdiRVRXXzRyUm1vNXhMRW9VX2o2emNBQVBfX1hEX2U0dyIsInJjaWQiOiIzZm14Z1k5NWpBd2oxYll2Q080VG9DTHliTGNZTmxOb0dhYVlzSWNyNE4wIiwiZmxvIjoyfQ.f-8XvPPgbnUZc-DY-gdHVeYw6wvabkN8fa_tNzlSQTMVB2x9IJW30vZVUqyP4LMDUDjWjlESEYE7ZQPg5qR0o0hv-eJcQkzopVY0vgRZF6B2GKCupxpm1Gitfxsh0LWAcF0tyZPV0Hvs8BP-mox9e-oQ0eziVe63kjUETskyQY4Ez1VLahExe7024c_qtx_WgmTNR5CwZcDF2bcUwOI2m9aYRopx79M0PAEx3QdUo4U81NGu33_0RZcJPDdiV6ts5P-bAaqpoSAY_IONmqNm6Vc8_T6Vy0Nu00FWZBtf9y64heLn8SLThf-vTflqLWnEPvrWfGbNjnjNWpdWAJimXA",
			expires: "2024-07-13T12:14:49.000Z",
			expiresIn: 86257054,
			unsafeLoggedOut: false,
			safe: true,
		},
		sessionRefreshFailed: false,
		sessionTracker:
			"ilnlormajjbpdgmpff.0.1720786631922.Z0FBQUFBQm1rUjdIRGYwVnVpdXJYSDZQVzFSR21jb2dNTi1CcVpQbzZDUlVjNlNGc1FnSnhLaVpTSS1oTmJ2MGJvTjdSV3RadW1aMzNWYS1mODZmWEFpNC1VVGhOLVBJSXFsRDYtdTZtQzYtMFJMcmdETVpRb1IxUElZUUdNZV9lNHp2T0s1bFVpcmE",
		temporaryGQL: { isEmployee: false, isLoggedIn: true },
		wallets: {},
		whitelist: {
			api: {},
			data: [
				{
					date: 1669767446,
					rel_id: "r9_4fq7lc",
					icon_img:
						"https://styles.redditmedia.com/t5_2f81p5/styles/profileIcon_snood1f07b06-9879-4de2-b91c-3f06a1db2063-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=d7b484e9aad68361beb5f87413e41d85c46683f9",
					name: "RA12220",
					id: "t2_5o2vw5g1",
				},
				{
					date: 1668810879,
					rel_id: "r9_4e5xfz",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_1.png",
					name: "RemindMeBot",
					id: "t2_gbm4p",
				},
				{
					date: 1668069511,
					rel_id: "r9_4cvk9z",
					icon_img:
						"https://styles.redditmedia.com/t5_49n5w9/styles/profileIcon_snoo5f9a49ef-95bb-4bcc-a504-18b28cb58a47-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=470d171e7c46aa8f08b7c80b95e83d139ba60a5d",
					name: "thebananaperson1",
					id: "t2_bcbz802b",
				},
				{
					date: 1666884712,
					rel_id: "r9_4awx1f",
					icon_img:
						"https://styles.redditmedia.com/t5_2wvxie/styles/profileIcon_snoo72413395-0900-4f33-b929-52fd34938ffb-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=2681d85bcc17c60719b42a1b476fdd2519381828",
					name: "mrcoo1",
					id: "t2_7fgjghic",
				},
				{
					date: 1666032614,
					rel_id: "r9_49im6x",
					icon_img: "https://www.redditstatic.com/avatars/defaults/v2/avatar_default_2.png",
					name: "throwawaydjdieiw",
					id: "t2_t2jmj9wi",
				},
				{
					date: 1664672045,
					rel_id: "r9_474rgo",
					icon_img:
						"https://styles.redditmedia.com/t5_6zqurc/styles/profileIcon_snoo3d853fbc-62c4-4f31-851a-f4837e6a9430-headshot.png?width=256\u0026height=256\u0026crop=256:256,smart\u0026s=07750aab65186e840747c62ab6f7d06706f533c5",
					name: "flufyyanal",
					id: "t2_s89gjbwc",
				},
			],
		},
	},
	userDataRequestPage: { userDataRequestPageApi: { error: null, pending: false, success: false, userDataExportEligibility: false } },
	upvotePromptCountPerSess: 0,
	users: {
		api: { error: {}, pending: false },
		appliedBadges: {},
		models: {},
		nameAvailable: {},
		topAwarders: { api: { error: null, pending: false }, currentPostId: null, currentRank: {}, list: {} },
		powerups: { fetched: false },
	},
	widgets: { idCardIds: {}, menuIds: {}, models: {}, moderatorIds: {}, sidebar: {} },
	features: {
		removalReasons: { api: { error: null, pending: false }, models: {}, reasonOrder: {}, removedItemIds: null },
		realtimeUpdateAnimationId: null,
		powerupsBenefitSettings: {},
		modActivitySummaries: {},
		eligibleUXExperiences: { experiences: {} },
		devPlatform: { formModal: { form: null, onSubmit: null }, userInputModal: { action: null, onAction: null } },
		activeCommunitiesOnProfile: {},
		matrixChat: { state: 0, url: "https://chat.reddit.com" },
		crypto: { claims: {}, points: {}, publicWallets: {} },
		happeningNow: {
			api: { error: null, loaded: false, pending: false },
			models: {},
			popular: [],
			recommended: [],
			selectedFilter: "all",
			showLiveContentAvailabilityTooltip: false,
			unread: { lastReadTimestampMs: 0, latestUnreadContentTimestampMs: 0 },
		},
		communityChat: { selectedChannelId: "", models: {}, channelIds: {}, hasShownToastMessage: false },
		categories: {
			api: { list: { error: null, loaded: false, pending: false }, subreddits: { error: {}, loaded: {}, pending: {} } },
			ids: [],
			models: {},
			nameToId: {},
			ranking: {},
		},
		powerups: { subredditPowerupsFlairs: {}, subredditUserPowerupsFlairs: {} },
		socialLinks: {},
		marketplace: { feedUnit: { id: null, title: "", description: "", buttonCtaText: "", feedIndex: 0 }, claimStatus: {}, linkPreview: {} },
		predictions: {
			creation: [],
			leaderboards: {},
			tournaments: {},
			tournamentsLeaderboards: {},
			tournamentsBySubreddit: {},
			queriedLeaderboards: {},
		},
		comments: {
			collapsed: {},
			drafts: {},
			focused: {},
			hidden: {},
			isEditing: {},
			models: {},
			replyFormOpen: {},
			submit: { error: {}, pending: {} },
			visitHighlightFilter: "Last",
		},
		goldPurchase: {
			packageOfferModal: { packageId: null },
			payment: {
				cardName: "",
				cardValidation: { cardCvc: "", cardExpiry: "", cardNumber: "", nameOnCard: "", postalCode: "" },
				paymentMethod: null,
				paypal: { errorMessage: null, passthrough: "" },
				postalCode: "",
				rememberCard: true,
				savedCards: [],
				savedCardsPending: false,
				stripeToken: { errorMessage: null, pending: false },
				useSavedCard: null,
			},
			premiumPurchaseModal: { activePage: "selectPayment", showModal: false, packageId: null, renewInterval: null },
			productOffers: {},
			purchaseCatalog: {
				activeSaleConfig: null,
				api: { errorMessage: null, recommendedPending: false, storefrontPending: false },
				coinPackages: { models: {}, dealPackageIds: [], recommendedPackageIds: [], storefrontPackageIds: [] },
				freeAwardEvent: null,
				premiumPackages: [],
			},
			purchaseModal: { activePage: "selectPayment", correlationId: null, gildThingId: null, packageId: null, showModal: false },
		},
		modUserNotes: {
			api: { error: null, pending: {} },
			fetchedTokens: {},
			lastAuthorModNotes: {},
			loadMore: {},
			models: {},
			order: {},
			totalCount: {},
		},
		userFlair: {},
		shouldTryToShowCrosspostModal: false,
		avatar: {
			marketing: null,
			avatarUser: {
				id: "",
				csrf_token: "",
				snoovatar: null,
				websocketsUrls: { renderer: "", download: "" },
				capabilities: ["PREMIUM"],
				hasActiveClosetSubscription: false,
			},
			randomAvatar: null,
		},
		creatorStats: { postOtherDiscussions: {}, postStats: {}, subredditKarma: {} },
		banned: {
			api: { error: null, pending: {} },
			fetchedTokens: {},
			inContext: null,
			loadMore: {},
			models: {},
			search: { api: { error: null, pending: false }, result: null },
			userOrder: {},
		},
		econPurchase: { subredditLockedCoins: {} },
		liveBar: { items: [] },
		modPreviousActions: { models: {}, order: {} },
		realtimeModqueue: { toUpdate: [], updated: [] },
		relatedCommunitiesRecommendations: {},
		reportFlow: {
			api: { error: {}, pending: {}, success: {} },
			openedFromModalPage: false,
			postOrCommentId: null,
			userIsMod: false,
			rulesCategory: null,
		},
	},
};

export type State = typeof initialState;

const addScript = (url: string): Promise<HTMLScriptElement> => {
	return new Promise((resolve, reject) => {
		const script = document.createElement("script");
		script.src = url;
		script.async = true;

		script.onload = () => {
			resolve(script);
		};

		script.onerror = () => {
			reject(new Error("Error loading script " + url));
		};

		document.body.appendChild(script);
	});
};

async function main() {
	await userscriptLoaded;

	logger.dbg("Userscript loaded, loading client...");

	initialState.user.loid = getLoidState();
	initialState.user.session = {
		accessToken: window.tokenCache.token,
		expires: new Date(window.tokenCache.expires).toISOString(),
		expiresIn: window.tokenCache.expires - Date.now(),
		unsafeLoggedOut: false,
		safe: true
	};

	(window as any).___r = initialState;

	const container: any = document.getElementById("2x-container");
	if (!container) {
		throw new Error("root container not found");
	}

	initAPIMigratorInterceptors();
	await addScript("https://www.redditstatic.com/desktop2x/Reddit.e6908df657b523d36c19.js");

	const timer = setInterval(() => {
		const store = container._reactRootContainer?._internalRoot?.current?.alternate?.memoizedState?.element?.props?.children?.props?.store;

		if (store) {
			window.store = store;
			logger.dbg("Redux store captured successfully!");
			clearInterval(timer);
			window.clientLoaded = true;
			// right now, I manually send it using a bookmarklet
			// window.dispatchEvent(new PopStateEvent('popstate'))
		}
	}, 50);

	setTimeout(() => {
		if (!window.store) throw new Error("Timed out trying to capture redux store. (>5 seconds)");
		clearInterval(timer);
	}, 5000);


	const redditDomains = new Set(['reddit.com', 'www.reddit.com', 'old.reddit.com', 'new.reddit.com', 'np.reddit.com', /* window.location.host */ ]);

	document.addEventListener('click', async (e: any) => {
		const anchor = e.target?.closest('a');
		if (!anchor || !anchor.href) return;

		const url = new URL(anchor.href);

		if (anchor.classList.contains("_3t5uN8xUmg0TOwRCOGQEcU") || (redditDomains.has(url.host) && (url.pathname.includes("/s/") || url.pathname.includes("/comments/")))) {
			e.preventDefault();

			let fullPath;

			if (url.hostname === "redd.it") {
				fullPath = "/comments" + url.pathname;
			} else if (url.pathname.includes("/s/")) {
				fullPath = new URL((await gqlFetch(
					"ShareUrl", "424a761fb3d80ef2ec18a7dfaa867a9a1acf44df218e526c4538850dc7415c86", { shortUrl: url.toString() }
				)).shareUrl.url).pathname;
			} else {
				fullPath = url.pathname + url.search + url.hash
			}

			logger.log(`Redirecting link to internal route: ${fullPath}`);
			//window.history.pushState(null, '', fullPath);
			window.store.dispatch({
				type: "@@router/CALL_HISTORY_METHOD",
				payload: {
					method: "push",
					args: [fullPath]
				}
			});

			// Tell React to re-render the view
			window.dispatchEvent(new PopStateEvent('popstate'));
		}
	}, true);
};

main();

export const getState = (): State => {
	return window.store!.getState() ?? initialState
}
